### ISSUE TITLE
请问本地知识的格式是什么？

### ISSUE THREAD

**Issue by robin087** [imClumsyPanda/langchain-ChatGLM#10]

**Comment by imClumsyPanda** [comment]
已测试格式包括docx、md文件中的文本信息，具体格式可以参考[langchain文档](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/unstructured_file.html?highlight=pdf#)

**Comment by robin087** [comment]
假如不需要读取图片数据的话，是否还需要安装detectron2库呢？

**Comment by imClumsyPanda** [comment]
@robin087 不需要的 把本项写入主要是因为 langchain 文档中提及

**Comment by robin087** [comment]
好的，谢谢，那我直接尝试一下

**Comment by cutelitchi** [comment]
> 已测试格式包括docx、md文件中的文本信息，具体格式可以参考 [langchain文档](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/unstructured_file.html?highlight=pdf#)

请问一下，向量化之后的数据目前是放在本地文件里，这块能否自定义改造一下存储到其他的向量数据库，请问是否有可行性？

**Comment by imClumsyPanda** [comment]
可以，langchain本身支持除了faiss之外的其他向量数据库，具体可以参考langchain文档

xiaoshan ***@***.***>于2023年5月4日 周四18:06写道：
