### ISSUE TITLE
24G的显存还是爆掉了，是否支持双卡运行

### ISSUE THREAD

**Issue by heguodui** [imClumsyPanda/langchain-ChatGLM#11]
RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 23.70 GiB total capacity; 22.18 GiB already allocated; 12.75 MiB free; 22.18 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by tutuxxx** [comment]
RuntimeError: CUDA out of memory. Tried to allocate 96.00 MiB (GPU 0; 22.38 GiB total capacity; 21.43 GiB already allocated; 19.94 MiB free; 21.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

同问

**Comment by imClumsyPanda** [comment]
请先参考一下 https://github.com/imClumsyPanda/langchain-ChatGLM/issues/9#issuecomment-1494028383 看能否解决

**Comment by tutuxxx** [comment]
> 请先参考一下 [#9 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/9#issuecomment-1494028383) 看能否解决

这样可以运行起来了。不过问第二个问题的时候程序会挂掉：Token indices sequence length is longer than the specified maximum sequence length for this model (4444 > 2048). Running this sequence through the model will result in indexing errors

**Comment by heguodui** [comment]
> > 请先参考一下 [#9 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/9#issuecomment-1494028383) 看能否解决
> 
> 这样可以运行起来了。不过问第二个问题的时候程序会挂掉：Token indices sequence length is longer than the specified maximum sequence length for this model (4444 > 2048). Running this sequence through the model will result in indexing errors

改完之后，报错

 File "/home/jfai/code/hgd/langchain-ChatGLM/chatglm_llm.py", line 67, in _call
    response, updated_history = self.model.chat(
AttributeError: 'NoneType' object has no attribute 'chat'

**Comment by GanymedeNil** [comment]
模型可以改成用chatglm-6b-int4，差不多初始6个G的显存占用

**Comment by imClumsyPanda** [comment]
已在 2023/04/07 更新中解决显存双倍占用的问题，并在 readme.md 中新增关于硬件占用的描述。

**Comment by imClumsyPanda** [comment]
已在 chatglm_llm.py 中新增 torch_gc 函数，实现每次调用模型生成问答后清理显存。

**Comment by imClumsyPanda** [comment]
昨晚提交了更新后的代码，有效减少2-3轮提问后可能存在内存爆掉的情况。

**Comment by Kino521** [comment]
OutOfMemoryError: CUDA out of memory. Tried to allocate 22.99 GiB (GPU 0; 39.56 
GiB total capacity; 22.99 GiB already allocated; 15.27 GiB free; 23.00 GiB 
reserved in total by PyTorch) If reserved memory is >> allocated memory try 
setting max_split_size_mb to avoid fragmentation.  See documentation for Memory 
Management and PYTORCH_CUDA_ALLOC_CONF
