### ISSUE TITLE
请问用的什么操作系统呢？

### ISSUE THREAD

**Issue by jackchenwen** [imClumsyPanda/langchain-ChatGLM#110]
ubuntu、centos还是windows？

**Comment by imClumsyPanda** [comment]
应该都可以

**Comment by buttercannfly** [comment]
Unknown platform: darwin

**Comment by imClumsyPanda** [comment]
@buttercannfly 请问有更详细的报错信息吗

**Comment by rocymp** [comment]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Unknown platform: darwin
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by buttercannfly** [comment]
To create a public link, set `share=True` in `launch()`.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Unknown platform: darwin
@imClumsyPanda

**Comment by ykk648** [comment]
check https://github.com/THUDM/ChatGLM-6B/issues/6
