### ISSUE TITLE
你怎么知道embeddings方式和模型训练时候的方式是一样的?

### ISSUE THREAD

**Issue by ruanshudong** [imClumsyPanda/langchain-ChatGLM#12]

**Comment by imClumsyPanda** [comment]
embedding和LLM的方式不用一致，embedding能够解决语义检索的需求就行。这个项目里用到embedding是在对本地知识建立索引和对问句转换成向量的过程。

**Comment by ruanshudong** [comment]
哦哦, 理解了, 这个不是finetune, 只是本地内容的检索
