### ISSUE TITLE
本地知识内容数量限制？

### ISSUE THREAD

**Issue by githubBingoChen** [imClumsyPanda/langchain-ChatGLM#129]
本地知识文件类型是txt，超过5条以上的数据，提问的时候就爆显存了。

**Comment by githubBingoChen** [comment]
https://modelscope.cn/datasets/simpleai/HC3-Chinese/dataPeview
知识文件参考上面链接的baike数据
![image](https://user-images.githubusercontent.com/16846991/232721466-209be505-0488-413b-b634-0684d896931b.png)

**Comment by imClumsyPanda** [comment]
如果单句长度过长，输入给llm时可能引起大量显存占用，可以考虑以下方式解决：

1 调整匹配上下文数量 top-k
2 调整分句方式，使单句长度更短
