### ISSUE TITLE
是否能提供本地知识文件的格式？

### ISSUE THREAD

**Issue by heguodui** [imClumsyPanda/langchain-ChatGLM#13]
是否能提供本地知识文件的格式？

**Comment by imClumsyPanda** [comment]
目前已测试支持的格式包括docx、md、pdf，更多格式信息可参考 [langchain 文档](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/unstructured_file.html?highlight=pdf )

**Comment by suc16** [comment]
给一个每行一条知识的txt即可，注意utf-8编码，以及里面不要有神奇的特殊符号（踩坑的痛啊。。。）
实际在调用partition_text函数，分element是根据换行符"\n"
https://github.com/Unstructured-IO/unstructured/blob/4211dda360dce4bfdfa60e580739eab4cbe8a729/unstructured/partition/text.py#L24

**Comment by heguodui** [comment]
> 给一个每行一条知识的txt即可，注意utf-8编码，以及里面不要有神奇的特殊符号（踩坑的痛啊。。。） 实际在调用partition_text函数，分element是根据换行符"\n" https://github.com/Unstructured-IO/unstructured/blob/4211dda360dce4bfdfa60e580739eab4cbe8a729/unstructured/partition/text.py#L24

十分感谢

**Comment by heguodui** [comment]
> 目前已测试支持的格式包括docx、md、pdf，更多格式信息可参考 [langchain 文档](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/unstructured_file.html?highlight=pdf)

感谢🙏

**Comment by GreatWildFire** [comment]
> > 目前已测试支持的格式包括docx、md、pdf，更多格式信息可参考 [langchain 文档](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/unstructured_file.html?highlight=pdf)
> 
> 感谢🙏

您好，请问txt的数据格式您是如何设置的，可否给出一个参考，我按照大家的说法对txt数据进行了调整，依然显示未能成功加载
content/data02.txt 未能成功加载
Traceback (most recent call last):
  File "D:\anaconda3\envs\langchai\lib\site-packages\gradio\routes.py", line 401, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\anaconda3\envs\langchai\lib\site-packages\gradio\blocks.py", line 1302, in process_api
    result = await self.call_function(
  File "D:\anaconda3\envs\langchai\lib\site-packages\gradio\blocks.py", line 1025, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\anaconda3\envs\langchai\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\anaconda3\envs\langchai\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\anaconda3\envs\langchai\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:/LLM/langchain-ChatGLM/webui.py", line 82, in get_vector_store
    vs_path = local_doc_qa.init_knowledge_vector_store(["content/" + filepath])
  File "E:\LLM\langchain-ChatGLM\chains\local_doc_qa.py", line 80, in init_knowledge_vector_store
    vector_store = FAISS.from_documents(docs, self.embeddings)
  File "D:\anaconda3\envs\langchai\lib\site-packages\langchain\vectorstores\base.py", line 116, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
  File "D:\anaconda3\envs\langchai\lib\site-packages\langchain\vectorstores\faiss.py", line 345, in from_texts
    return cls.__from(texts, embeddings, embedding, metadatas, **kwargs)
  File "D:\anaconda3\envs\langchai\lib\site-packages\langchain\vectorstores\faiss.py", line 307, in __from
    index = faiss.IndexFlatL2(len(embeddings[0]))
IndexError: list index out of range

**Comment by imClumsyPanda** [comment]
@GreatWildFire 请问时使用最新版代码的运行结果吗

**Comment by hyb1234hi** [comment]
知识库是类似langchain的state_of_the_union.txt文件吗

**Comment by imClumsyPanda** [comment]
目前对本地知识文件只有文件格式要求，docx\txt\pdf\md可以，除此之外，建议文件中文本是有清晰分句标点符号的，比如句号、问号、叹号，因为目前实现原理要首先进行分句。

hyb1234hi ***@***.***>于2023年4月28日 周五14:48写道：

**Comment by hyb1234hi** [comment]
加了state_of_the_union.txt的知识库，回答效果很差，是知识库数据太少的原因吗

**Comment by deserteagle369** [comment]
如果一条知识有多行，换行要用软回车吗？

**Comment by imClumsyPanda** [comment]
均可

Gavin ***@***.***>于2023年5月8日 周一13:10写道：

**Comment by AlexYoung757** [comment]
可否支持多个文档

**Comment by imClumsyPanda** [comment]
现在就是支持的

DataAnalysist ***@***.***>于2023年5月17日 周三09:35写道：

**Comment by net592** [comment]
2、VPN如何安装下载？
登录XX官网可以下载网站地址(vpn.xx.com）
问题：返回结果 网站 vpn. xx. com每个都好有一个空格，被切割了

**Comment by zj2050** [comment]
> 给一个每行一条知识的txt即可，注意utf-8编码，以及里面不要有神奇的特殊符号（踩坑的痛啊。。。） 实际在调用partition_text函数，分element是根据换行符"\n" https://github.com/Unstructured-IO/unstructured/blob/4211dda360dce4bfdfa60e580739eab4cbe8a729/unstructured/partition/text.py#L24

知识库文档结构，能写个有问题和答案的例子么？ 比如：你是谁？我是langchain，这个是一行还是两行？

**Comment by jethand** [comment]
本地知识库如果是类似
Q：怎么获取xxxApi
A：几句话的文档

此类问题如果使用LLM效果有点儿辣眼睛，但是当作检索工具来用的话感觉还行

**Comment by MarielMa** [comment]
我上传好几个pdf文件，都不支持，怎么回事啊

**Comment by HelloJack0** [comment]
有没有测试出什么样的格式效果好，我测试的效果，答案会包含其他问题的答案，知识库测试时选择只返回一条数据，看上去是准的，但是知识库对话的时候又会总结很多其他问题的答案一起返回
