### ISSUE TITLE
我本来也计划做一个类似的产品，看来不用从头开始做了

### ISSUE THREAD

**Issue by yyaadet** [imClumsyPanda/langchain-ChatGLM#130]
文本切割，还有优化空间吗？微信群已经加不进去了。

**Comment by imClumsyPanda** [comment]
xiaotao.peng ***@***.***>于2023年4月18日 周二16:52写道：

**Comment by Wanger-SJTU** [comment]
超过两百人了，加不进去了

**Comment by imClumsyPanda** [comment]
![qr_code](https://user-images.githubusercontent.com/5668498/232780711-27ba4d05-18b4-4107-995a-4901d7693f4d.jpg)

**Comment by imClumsyPanda** [comment]
> 文本切割，还有优化空间吗？微信群已经加不进去了。

如果已经加群了，欢迎私信我，可以一起研究一下优化实现
