### ISSUE TITLE
No sentence-transformers model found with name ‘/text2vec/‘，但是再路径下面确实有模型文件

### ISSUE THREAD

**Issue by ct1976** [imClumsyPanda/langchain-ChatGLM#145]
另外：The dtype of attention mask (torch.int64) is not bool

**Comment by tomsux** [comment]
> 另外：The dtype of attention mask (torch.int64) is not bool

解决了吗

**Comment by imClumsyPanda** [comment]
标题中信息是warning不影响使用

tomsux ***@***.***>于2023年4月20日 周四16:45写道：

**Comment by alfgo** [comment]
我也报这个错No sentence-transformers model found with name ‘/text2vec/‘

**Comment by alfgo** [comment]
@ct1976  这个报错解决了吗
