### ISSUE TITLE
No sentence-transformers model found with name GanymedeNil/text2vec-large-chinese. Creating a new one with MEAN pooling

### ISSUE THREAD

**Issue by alfgo** [imClumsyPanda/langchain-ChatGLM#156]
ls GanymedeNil/text2vec-large-chinese
config.json  eval_results.txt  pytorch_model.bin  special_tokens_map.json  tokenizer.json  tokenizer_config.json  vocab.txt

明明目录下有文件，奇怪了

**Comment by onesecurity** [comment]
Same question

**Comment by 612twilight** [comment]
因为这个是huggingface的模型，不符合sentence transformer的规范，所以warn一下，但是结果依然可以用

**Comment by imClumsyPanda** [comment]
是个warning 不是error 不影响正常使用

**Comment by HIT-Owen** [comment]
> 因为这个是huggingface的模型，不符合sentence transformer的规范，所以warn一下，但是结果依然可以用

直接复制一个pooling文件过来就不会警告了，但是其实不影响使用

**Comment by Sowhat007** [comment]
> > 因为这个是huggingface的模型，不符合sentence transformer的规范，所以warn一下，但是结果依然可以用
> 
> 直接复制一个pooling文件过来就不会警告了，但是其实不影响使用

复制pooling和module.json过来会报错，会找你要sentence_xlnet_config.json
不管他就好了。

**Comment by wgq1134711420** [comment]
> 是个warning 不是error 不影响正常使用

通过单独加载 ChatGLM和text2vec-large-chinese 发现有这个警告  text2vec-large-chinese模型并没有加载到显存

**Comment by 141forever** [comment]
> 因为这个是huggingface的模型，不符合sentence transformer的规范，所以warn一下，但是结果依然可以用

非常感谢
