### ISSUE TITLE
embedding会加载两次

### ISSUE THREAD

**Issue by zhihao-chen** [imClumsyPanda/langchain-ChatGLM#159]
你好，为什么要这样设置呢，这样会加载两次呀。
self.embeddings = HuggingFaceEmbeddings(model_name=embedding_model_dict[embedding_model], )
self.embeddings.client = sentence_transformers.SentenceTransformer(self.embeddings.model_name,
                                                                           device=embedding_device)
HuggingfaceEmbeddings中原本就是用sentence_transformers加载的：
    def __init__(self, **kwargs: Any):
        """Initialize the sentence_transformer."""
        super().__init__(**kwargs)
        try:
            import sentence_transformers

            self.client = sentence_transformers.SentenceTransformer(self.model_name)
        except ImportError:
            raise ValueError(
                "Could not import sentence_transformers python package. "
                "Please install it with `pip install sentence_transformers`."
            )

**Comment by imClumsyPanda** [comment]
这一步主要是为了设置embedding的运行设备，最新版本的langchain中已经更新，可以在初始化时直接设置，所以本项目下一版本中也将会更新

zhihao-chen ***@***.***>于2023年4月23日 周日11:39写道：

**Comment by zhihao-chen** [comment]
ok，另外你了解为什么使用ConversationalRetrievalChain就会OOM吗。我自己测试时，居然提醒我需要400多G

**Comment by imClumsyPanda** [comment]
需要多次、频繁调用llm，如果llm不是api或者没有先初始化，会消耗很多资源

zhihao-chen ***@***.***>于2023年4月23日 周日11:45写道：
