### ISSUE TITLE
执行python3 cli_demo.py 报错AttributeError: 'NoneType' object has no attribute 'chat'

### ISSUE THREAD

**Issue by wolfsecond** [imClumsyPanda/langchain-ChatGLM#163]
刚开始怀疑是内存不足问题，换成int4,int4-qe也不行，有人知道是什么原因吗
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/engine/git_code/langchain-ChatGLM/cli_demo.py:31 in <module>                               │
│                                                                                                  │
│   28 │   history = []                                                                            │
│   29 │   while True:                                                                             │
│   30 │   │   query = input("Input your question 请输入问题：")                                   │
│ ❱ 31 │   │   resp, history = local_doc_qa.get_knowledge_based_answer(query=query,                │
│   32 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   vs_path=vs_path,            │
│   33 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   chat_history=history)       │
│   34 │   │   if REPLY_WITH_SOURCE:                                                               │
│                                                                                                  │
│ /home/engine/git_code/langchain-ChatGLM/chains/local_doc_qa.py:137 in get_knowledge_based_answer │
│                                                                                                  │
│   134 │   │                                                                                      │
│   135 │   │   knowledge_chain.return_source_documents = True                                     │
│   136 │   │                                                                                      │
│ ❱ 137 │   │   result = knowledge_chain({"query": query})                                         │
│   138 │   │   self.llm.history[-1][0] = query                                                    │
│   139 │   │   return result, self.llm.history                                                    │
│   140                                                                                            │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/base.py:116 in __call__        │
│                                                                                                  │
│   113 │   │   │   outputs = self._call(inputs)                                                   │
│   114 │   │   except (KeyboardInterrupt, Exception) as e:                                        │
│   115 │   │   │   self.callback_manager.on_chain_error(e, verbose=self.verbose)                  │
│ ❱ 116 │   │   │   raise e                                                                        │
│   117 │   │   self.callback_manager.on_chain_end(outputs, verbose=self.verbose)                  │
│   118 │   │   return self.prep_outputs(inputs, outputs, return_only_outputs)                     │
│   119                                                                                            │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/base.py:113 in __call__        │
│                                                                                                  │
│   110 │   │   │   verbose=self.verbose,                                                          │
│   111 │   │   )                                                                                  │
│   112 │   │   try:                                                                               │
│ ❱ 113 │   │   │   outputs = self._call(inputs)                                                   │
│   114 │   │   except (KeyboardInterrupt, Exception) as e:                                        │
│   115 │   │   │   self.callback_manager.on_chain_error(e, verbose=self.verbose)                  │
│   116 │   │   │   raise e                                                                        │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/retrieval_qa/base.py:110 in    │
│ _call                                                                                            │
│                                                                                                  │
│   107 │   │   question = inputs[self.input_key]                                                  │
│   108 │   │                                                                                      │
│   109 │   │   docs = self._get_docs(question)                                                    │
│ ❱ 110 │   │   answer = self.combine_documents_chain.run(                                         │
│   111 │   │   │   input_documents=docs, question=question                                        │
│   112 │   │   )                                                                                  │
│   113                                                                                            │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/base.py:216 in run             │
│                                                                                                  │
│   213 │   │   │   return self(args[0])[self.output_keys[0]]                                      │
│   214 │   │                                                                                      │
│   215 │   │   if kwargs and not args:                                                            │
│ ❱ 216 │   │   │   return self(kwargs)[self.output_keys[0]]                                       │
│   217 │   │                                                                                      │
│   218 │   │   raise ValueError(                                                                  │
│   219 │   │   │   f"`run` supported with either positional arguments or keyword arguments"       │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/base.py:116 in __call__        │
│                                                                                                  │
│   113 │   │   │   outputs = self._call(inputs)                                                   │
│   114 │   │   except (KeyboardInterrupt, Exception) as e:                                        │
│   115 │   │   │   self.callback_manager.on_chain_error(e, verbose=self.verbose)                  │
│ ❱ 116 │   │   │   raise e                                                                        │
│   117 │   │   self.callback_manager.on_chain_end(outputs, verbose=self.verbose)                  │
│   118 │   │   return self.prep_outputs(inputs, outputs, return_only_outputs)                     │
│   119                                                                                            │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/base.py:113 in __call__        │
│                                                                                                  │
│   110 │   │   │   verbose=self.verbose,                                                          │
│   111 │   │   )                                                                                  │
│   112 │   │   try:                                                                               │
│ ❱ 113 │   │   │   outputs = self._call(inputs)                                                   │
│   114 │   │   except (KeyboardInterrupt, Exception) as e:                                        │
│   115 │   │   │   self.callback_manager.on_chain_error(e, verbose=self.verbose)                  │
│   116 │   │   │   raise e                                                                        │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/combine_documents/base.py:75   │
│ in _call                                                                                         │
│                                                                                                  │
│    72 │   │   docs = inputs[self.input_key]                                                      │
│    73 │   │   # Other keys are assumed to be needed for LLM prediction                           │
│    74 │   │   other_keys = {k: v for k, v in inputs.items() if k != self.input_key}              │
│ ❱  75 │   │   output, extra_return_dict = self.combine_docs(docs, **other_keys)                  │
│    76 │   │   extra_return_dict[self.output_key] = output                                        │
│    77 │   │   return extra_return_dict                                                           │
│    78                                                                                            │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/combine_documents/stuff.py:83  │
│ in combine_docs                                                                                  │
│                                                                                                  │
│   80 │   │   """Stuff all documents into one prompt and pass to LLM."""                          │
│   81 │   │   inputs = self._get_inputs(docs, **kwargs)                                           │
│   82 │   │   # Call predict on the LLM.                                                          │
│ ❱ 83 │   │   return self.llm_chain.predict(**inputs), {}                                         │
│   84 │                                                                                           │
│   85 │   async def acombine_docs(                                                                │
│   86 │   │   self, docs: List[Document], **kwargs: Any                                           │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/llm.py:151 in predict          │
│                                                                                                  │
│   148 │   │   │   │                                                                              │
│   149 │   │   │   │   completion = llm.predict(adjective="funny")                                │
│   150 │   │   """                                                                                │
│ ❱ 151 │   │   return self(kwargs)[self.output_key]                                               │
│   152 │                                                                                          │
│   153 │   async def apredict(self, **kwargs: Any) -> str:                                        │
│   154 │   │   """Format prompt with kwargs and pass to LLM.                                      │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/base.py:116 in __call__        │
│                                                                                                  │
│   113 │   │   │   outputs = self._call(inputs)                                                   │
│   114 │   │   except (KeyboardInterrupt, Exception) as e:                                        │
│   115 │   │   │   self.callback_manager.on_chain_error(e, verbose=self.verbose)                  │
│ ❱ 116 │   │   │   raise e                                                                        │
│   117 │   │   self.callback_manager.on_chain_end(outputs, verbose=self.verbose)                  │
│   118 │   │   return self.prep_outputs(inputs, outputs, return_only_outputs)                     │
│   119                                                                                            │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/base.py:113 in __call__        │
│                                                                                                  │
│   110 │   │   │   verbose=self.verbose,                                                          │
│   111 │   │   )                                                                                  │
│   112 │   │   try:                                                                               │
│ ❱ 113 │   │   │   outputs = self._call(inputs)                                                   │
│   114 │   │   except (KeyboardInterrupt, Exception) as e:                                        │
│   115 │   │   │   self.callback_manager.on_chain_error(e, verbose=self.verbose)                  │
│   116 │   │   │   raise e                                                                        │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/llm.py:57 in _call             │
│                                                                                                  │
│    54 │   │   return [self.output_key]                                                           │
│    55 │                                                                                          │
│    56 │   def _call(self, inputs: Dict[str, Any]) -> Dict[str, str]:                             │
│ ❱  57 │   │   return self.apply([inputs])[0]                                                     │
│    58 │                                                                                          │
│    59 │   def generate(self, input_list: List[Dict[str, Any]]) -> LLMResult:                     │
│    60 │   │   """Generate LLM result from inputs."""                                             │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/llm.py:118 in apply            │
│                                                                                                  │
│   115 │                                                                                          │
│   116 │   def apply(self, input_list: List[Dict[str, Any]]) -> List[Dict[str, str]]:             │
│   117 │   │   """Utilize the LLM generate method for speed gains."""                             │
│ ❱ 118 │   │   response = self.generate(input_list)                                               │
│   119 │   │   return self.create_outputs(response)                                               │
│   120 │                                                                                          │
│   121 │   async def aapply(self, input_list: List[Dict[str, Any]]) -> List[Dict[str, str]]:      │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/chains/llm.py:62 in generate          │
│                                                                                                  │
│    59 │   def generate(self, input_list: List[Dict[str, Any]]) -> LLMResult:                     │
│    60 │   │   """Generate LLM result from inputs."""                                             │
│    61 │   │   prompts, stop = self.prep_prompts(input_list)                                      │
│ ❱  62 │   │   return self.llm.generate_prompt(prompts, stop)                                     │
│    63 │                                                                                          │
│    64 │   async def agenerate(self, input_list: List[Dict[str, Any]]) -> LLMResult:              │
│    65 │   │   """Generate LLM result from inputs."""                                             │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/llms/base.py:107 in generate_prompt   │
│                                                                                                  │
│   104 │   │   self, prompts: List[PromptValue], stop: Optional[List[str]] = None                 │
│   105 │   ) -> LLMResult:                                                                        │
│   106 │   │   prompt_strings = [p.to_string() for p in prompts]                                  │
│ ❱ 107 │   │   return self.generate(prompt_strings, stop=stop)                                    │
│   108 │                                                                                          │
│   109 │   async def agenerate_prompt(                                                            │
│   110 │   │   self, prompts: List[PromptValue], stop: Optional[List[str]] = None                 │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/llms/base.py:140 in generate          │
│                                                                                                  │
│   137 │   │   │   │   output = self._generate(prompts, stop=stop)                                │
│   138 │   │   │   except (KeyboardInterrupt, Exception) as e:                                    │
│   139 │   │   │   │   self.callback_manager.on_llm_error(e, verbose=self.verbose)                │
│ ❱ 140 │   │   │   │   raise e                                                                    │
│   141 │   │   │   self.callback_manager.on_llm_end(output, verbose=self.verbose)                 │
│   142 │   │   │   return output                                                                  │
│   143 │   │   params = self.dict()                                                               │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/llms/base.py:137 in generate          │
│                                                                                                  │
│   134 │   │   │   │   {"name": self.__class__.__name__}, prompts, verbose=self.verbose           │
│   135 │   │   │   )                                                                              │
│   136 │   │   │   try:                                                                           │
│ ❱ 137 │   │   │   │   output = self._generate(prompts, stop=stop)                                │
│   138 │   │   │   except (KeyboardInterrupt, Exception) as e:                                    │
│   139 │   │   │   │   self.callback_manager.on_llm_error(e, verbose=self.verbose)                │
│   140 │   │   │   │   raise e                                                                    │
│                                                                                                  │
│ /home/engine/.local/lib/python3.10/site-packages/langchain/llms/base.py:324 in _generate         │
│                                                                                                  │
│   321 │   │   # TODO: add caching here.                                                          │
│   322 │   │   generations = []                                                                   │
│   323 │   │   for prompt in prompts:                                                             │
│ ❱ 324 │   │   │   text = self._call(prompt, stop=stop)                                           │
│   325 │   │   │   generations.append([Generation(text=text)])                                    │
│   326 │   │   return LLMResult(generations=generations)                                          │
│   327                                                                                            │
│                                                                                                  │
│ /home/engine/git_code/langchain-ChatGLM/models/chatglm_llm.py:72 in _call                        │
│                                                                                                  │
│    69 │   def _call(self,                                                                        │
│    70 │   │   │     prompt: str,                                                                 │
│    71 │   │   │     stop: Optional[List[str]] = None) -> str:                                    │
│ ❱  72 │   │   response, _ = self.model.chat(                                                     │
│    73 │   │   │   self.tokenizer,                                                                │
│    74 │   │   │   prompt,                                                                        │
│    75 │   │   │   history=self.history[-self.history_len:] if self.history_len>0 else [],        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'chat'

**Comment by imClumsyPanda** [comment]
按照报错信息应该是模型初始化失败

wolfsecond ***@***.***>于2023年4月24日 周一11:20写道：

**Comment by Bo-LiangD** [comment]
这个问题怎么解决的呢
