### ISSUE TITLE
匹配得分

### ISSUE THREAD

**Issue by Vincent131499** [imClumsyPanda/langchain-ChatGLM#167]
在示例cli_demo.py中返回的匹配文本没有对应的score，可以加上这个feature吗

**Comment by imClumsyPanda** [comment]
好的 我看一下

MeteorMan ***@***.***>于2023年4月24日 周一19:39写道：

**Comment by imClumsyPanda** [comment]
在最新版的v0.1.6中已经可以返回了，但是因为没有归一化，所以没有默认显示，输出方式可以参考cli_demo.py第40行注释的代码
