### ISSUE TITLE
Is it possible to use a verctorDB for the embedings? 

### ISSUE THREAD

**Issue by dongwangdw** [imClumsyPanda/langchain-ChatGLM#171]
when I play, I have to load the local data again and again when to start. I wonder if it is possible to use
a vectorDB to store all the info.

And it is possible to seperate vectorBD and model?  So that I can keep feeding more and more data to DB without affecting
other parts.

**Comment by imClumsyPanda** [comment]
Now the web UI is implemented with the separated method, cli_demo has not
been updated. Will update in recent update.

Wang Dong ***@***.***>于2023年4月25日 周二14:03写道：

**Comment by dongwangdw** [comment]
@imClumsyPanda I have inspected the webui.py. It looks like no vectorDB used too, just files.

I wonder what do you mean by "seperated method"?

**Comment by imClumsyPanda** [comment]
There’s a selectbox to choose which knowledge base to use

Wang Dong ***@***.***>于2023年4月26日 周三10:12写道：
