### ISSUE TITLE
请问通过lora训练官方模型得到的微调模型文件该如何加载？

### ISSUE THREAD

**Issue by forgot-glory** [imClumsyPanda/langchain-ChatGLM#173]
通过lora训练的方式得到以下文件:
![image](https://user-images.githubusercontent.com/35793823/234215007-1bc9a163-5d7e-42b4-a0ff-20c07dda700d.png)
，我该如何在web_ui.py中加载该微调模型？

**Comment by glide-the** [comment]
dev-llmf分支查看项目启动参数models/loader/args.py
