### ISSUE TITLE
哪里有knowledge_based_chatglm.py文件？怎么找不到了？？是被替换成cli_demo.py文件了吗？

### ISSUE THREAD

**Issue by LOGIC-10** [imClumsyPanda/langchain-ChatGLM#175]
哪里有knowledge_based_chatglm.py文件？怎么找不到了？？是被替换成cli_demo.py文件了吗？

**Comment by imClumsyPanda** [comment]
是的

Qinyu Luo ***@***.***>于2023年4月26日 周三09:33写道：
