### ISSUE TITLE
控制台调api.py报警告

### ISSUE THREAD

**Issue by wuhu6** [imClumsyPanda/langchain-ChatGLM#178]
you must pass the application as an import string to enable "reload" or "workers"

这是啥原因呢

**Comment by cristianohello** [comment]
+1。项目怎么老是报错，之前还好好的

**Comment by imClumsyPanda** [comment]
请问方便提供一下具体报错截图吗

**Comment by wuhu6** [comment]
![image](https://user-images.githubusercontent.com/77470828/234538026-d4fa62e9-873e-4961-9f4f-6128e5a80b1a.png)

**Comment by cristianohello** [comment]
执行api.py脚本，就报错。很奇怪，之前好好的

**Comment by wuhu6** [comment]
> 执行api.py脚本，就报错。很奇怪，之前好好的

你是之前api.py能用吗？

**Comment by cristianohello** [comment]
一星期前的老版本能用，现在的新版本不能用

**Comment by JohnHello** [comment]
这个能解决启动问题，但是后续还有别的问题


if __name__ == "__main__":
    uvicorn.run(
        app="__mp_main__:app",
        host='0.0.0.0', 
        port=8082,
        reload=True,
        )

**Comment by cristianohello** [comment]
@imClumsyPanda 
这个api.py脚本错误修复了吗？

**Comment by cristianohello** [comment]
@JohnHello 
还有什么问题？

**Comment by kinget007** [comment]
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        app='api:app',
        host='0.0.0.0', 
        port=8100,
        reload=True
        )
