### ISSUE TITLE
请教一下langchain协调使用向量库和chatGLM工作的

### ISSUE THREAD

**Issue by wjjc1017** [imClumsyPanda/langchain-ChatGLM#18]
代码里面这段是创建问答模型的，会接入ChatGLM和本地语料的向量库，langchain回答的时候是怎么个优先顺序？先搜向量库，没有再找chatglm么？ 还是什么机制？
 knowledge_chain = ChatVectorDBChain.from_llm(
        llm=chatglm,
        vectorstore=vector_store,
        qa_prompt=prompt,
        condense_question_prompt=new_question_prompt,
    )

**Comment by imClumsyPanda** [comment]
实现中基本过程如下

文档加载➡️文本分段➡️embedding进行各段文本向量化形成vector_store➡️embedding对问句向量化并与vector_store中向量比较➡️匹配出的文本作为上下文与问句一起放入prompt模板中➡️prompt发送给llm获取回答

具体匹配排序机制可以在langchain的函数中找找看

**Comment by wjjc1017** [comment]
谢谢 了解了 构建的语料都是本地，搜索问题相关文本，然后将结果让LLM模型做语言优化和改写，返回答案。这样就不涉及语料之外的问题回答。
