### ISSUE TITLE
如何将Chatglm和本地知识相结合

### ISSUE THREAD

**Issue by Puzzledyy** [imClumsyPanda/langchain-ChatGLM#185]
您好，我想请教一下怎么才能让知识库匹配到的文本和chatglm生成的相结合，而不是说如果没搜索到，就说根据已知信息无法回答该问题，谢谢

**Comment by imClumsyPanda** [comment]
可以尝试修改一下Prompt模版，在语言描述中体现融合内容的需求

Rayford Bergreen ***@***.***>于2023年4月27日 周四12:25写道：

**Comment by Puzzledyy** [comment]
明白了 感谢

**Comment by cristianohello** [comment]
@imClumsyPanda 
怎么设计模板，才能让匹配到的内容和模型输出的内容一起都作为最终的回复内容？

**Comment by imClumsyPanda** [comment]
@cristianohello 这个问题恐怕连模型设计者都不一定能保证准确的回答出来

建议结合自己手头的知识库内容试试看
