### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by Harry-Lucas** [imClumsyPanda/langchain-ChatGLM#189]
1.weiui的get_vector_store方法里面添加一个判断以兼容gradio版本导致的上传异常
  if isinstance(files,list)==False:
      files=[files]
2.get_knowledge_based_answer方法generate_prompt(related_docs, query)添加生成promot限制.不然会导致promot过长内存报错

**Comment by imClumsyPanda** [comment]
收到 感谢

Harry-Lucas ***@***.***>于2023年4月27日 周四15:09写道：

**Comment by imClumsyPanda** [comment]
已通过chunk_size方式进行长度限制
