### ISSUE TITLE
加载doc后覆盖原本知识

### ISSUE THREAD

**Issue by ChenBinfighting1** [imClumsyPanda/langchain-ChatGLM#201]
加载较大量级的私有知识库后，原本的知识会被覆盖
问题：“你是谁”
回答：“根据已知信息，我无法回答该问题。没有提供足够的相关信息，无法确定身份或地区。请提供更多信息，以便我能够更好地帮助您。”

**Comment by imClumsyPanda** [comment]
大概是依据检索出的知识不能回答这个问题 并不是覆盖

BinChen ***@***.***>于2023年4月28日 周五15:05写道：
