### ISSUE TITLE
[FEATURE] 支持 RWKV 模型（目前已有 pip package & rwkv.cpp 等等）

### ISSUE THREAD

**Issue by BlinkDL** [imClumsyPanda/langchain-ChatGLM#216]
您好，我是 RWKV 的作者，介绍见：https://zhuanlan.zhihu.com/p/626083366

RWKV也有langchain 能力，不过prompt的格式有点区别，欢迎大家一起合作加入 RWKV 的支持 :)

目前支持 RWKV 的中英文界面有：
* 闻达：https://github.com/l15y/wenda
* Gradio DEMO: https://huggingface.co/spaces/BlinkDL/Raven-RWKV-7B
* ooba：https://github.com/oobabooga/text-generation-webui/issues/1401

使用方法：
* pip package: https://pypi.org/project/rwkv/
* 问答DEMO代码：https://github.com/BlinkDL/ChatRWKV/blob/main/v2/benchmark_more.py
* 聊天代码：https://github.com/BlinkDL/ChatRWKV
* CPU INT4/8 量化运行: https://github.com/saharNooby/rwkv.cpp

**Comment by imClumsyPanda** [comment]
您好，感谢您发来的邀约🙏

我们几位开发人员也很乐意支持各类模型，近期我们测试看看，如果有不顺利之处再跟您沟通。

**Comment by Galaxy-Ding** [comment]
我们 也在期待着

**Comment by exceedzhang** [comment]
请问是否已支持rwkv？目前在LMsys.org排名超过ChatGLM-6b模型

**Comment by FlyForFun-S** [comment]
> 已通过支持fastchat api调用的方式增加对RWKV模型的支持。

使用fastchat api调用时，RWKV模型的部署环境时什么呢（操作系统、显卡、CUDA版本、驱动的版本）
