### ISSUE TITLE
问一下chat_history的逻辑

### ISSUE THREAD

**Issue by YYGe01** [imClumsyPanda/langchain-ChatGLM#22]
感谢开源。
看了下chat_history的逻辑，就是把之前所有轮的历史，让chatglm合并成一个question。
这种情况下：
如果对话历史很多轮，现在问的和老早之前的历史假设没有什么关联了，那生成的新的question会不会不准确了。
那有什么办法可以知道当前聊的问题是一轮新的问题，而跟之前的问题没有关联了。

**Comment by imClumsyPanda** [comment]
这个有计划在下一步进行改进，但是最近测试环境一直有问题，还没来得及更新。
