### ISSUE TITLE
为什么每次运行都会loading checkpoint

### ISSUE THREAD

**Issue by Dhaizei** [imClumsyPanda/langchain-ChatGLM#23]
我把这个embeding模型下载到本地后，无法正常启动。
原代码每次运行代码都会提示这个
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:26<00:00, 13.11s/it]
/home/rgzn/miniconda3/envs/langchain/lib/python3.9/site-packages/langchain/chains/conversational_retrieval/base.py:192: UserWarning: `ChatVectorDBChain` is deprecated - please use `from langchain.chains import ConversationalRetrievalChain`
  warnings.warn

**Comment by imClumsyPanda** [comment]
因为chatglm-6b和embedding模型文件都是分成多个二进制文件存储的，所以加载过程中应该都会有多个checkpoint

**Comment by chenkexv** [comment]
如何加载微调的checkpoint呢，翻了所有文档也没看到，跪求大佬解答下
