### ISSUE TITLE
不支持txt文件的中文输入

### ISSUE THREAD

**Issue by fabulousfeng** [imClumsyPanda/langchain-ChatGLM#235]
vs_path, _ = local_doc_qa.init_knowledge_vector_store(filepath)

![image](https://user-images.githubusercontent.com/15232969/236215364-c64ca6ac-1398-47e1-ab1a-b3275766b241.png)
1.txt有中文就出现 'ascii' codec can't decode byte 0xe4 in position 0: ordinal not in range(128) 错误

**Comment by xlcaptain** [comment]
我也是这个问题

**Comment by xlcaptain** [comment]
添加了知识库之后进行对话，之后再新增知识库就会出现这个问题。如果是一直新增知识库，没有对话是可以新增上去的。

**Comment by fabulousfeng** [comment]
> 添加了知识库之后进行对话，之后再新增知识库就会出现这个问题。如果是一直新增知识库，没有对话是可以新增上去的。

我这init就不行

**Comment by xingxing3230** [comment]
unstructured == 0.6.1
unstructured-inference == 0.4.2
这两个包更新为这个版本，可以解决该问题

**Comment by Mr-IT007** [comment]
我想把文件字符的编码格式改为encoding='utf-8'在哪修改呢

**Comment by wujiekd** [comment]
> 添加了知识库之后进行对话，之后再增加知识库就会出现这个问题。如果是一直新增加知识库，没有对话是可以新增加上的去的。

我也是这个问题，
请问解决了吗

**Comment by ffy-FFRain** [comment]
更新包版本之后没有生效

**Comment by xingxing3230** [comment]
80%情况下，重启能解决该问题

**Comment by imClumsyPanda** [comment]
最新版更新为自动监测txt encoding类型。
