### ISSUE TITLE
文件均未成功加载，请检查依赖包或替换为其他文件再次上传。 文件未成功加载，请重新上传文件

### ISSUE THREAD

**Issue by DAODIXINGBU** [imClumsyPanda/langchain-ChatGLM#237]
请大佬帮忙解决，谢谢！
配置后，启动都没问题，但加载PDF文件时会出现不能加载的问题

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:11<00:00,  1.44s/it]
No sentence-transformers model found with name /root/.cache/torch/sentence_transformers/GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
模型已成功重新加载，可以开始对话，或从右侧选择模式后开始对话
There was a problem importing unstructured_inference module - it may not be installed correctly... try running pip install unstructured[local-inference] if you installed the unstructured library as a package. If you cloned the unstructured repository, try running make install-local-inference from the root directory of the repository.
/root/autodl-tmp/langchain-ChatGLM/content/industry_code_GMSe-200-30-07.pdf 未能成功加载
文件均未成功加载，请检查依赖包或替换为其他文件再次上传。
文件未成功加载，请重新上传文件

**Comment by imClumsyPanda** [comment]
可以按照报错信息 try running pip install unstructured[local-inference] 试试

DAODIXINGBU ***@***.***>于2023年5月5日 周五11:02写道：

**Comment by DAODIXINGBU** [comment]
我之前安装过了，但又安装了一遍后，无法新建知识库，并且出现error。我打算重新部署一下再试试！非常感谢！

**Comment by puretimeless** [comment]
怎么处理的，我上传txt也是提示的这个

**Comment by fatsand** [comment]
错误原因如果是："No module named 'charset_normalizer.md__mypyc.'" 
可以试试：
python -m pip install charset-normalizer==2.1.0
