### ISSUE TITLE
[BUG] 使用多卡时chatglm模型加载两次

### ISSUE THREAD

**Issue by potong** [imClumsyPanda/langchain-ChatGLM#241]
![image](https://user-images.githubusercontent.com/10555409/236391955-c3d9168d-6610-4dfc-9a49-1dcc0efef415.png)

**Comment by potong** [comment]
chatglm_llm.py文件下第129行先加载了一次chatglm模型，第143行又加载了一次

**Comment by potong** [comment]
![image](https://user-images.githubusercontent.com/10555409/236392948-8633b798-66fc-4223-9a1c-3d0cd93bd6e7.png)

做了相应修改

**Comment by imClumsyPanda** [comment]
上次被提交pr时疏漏了 感谢指出

TianMin ***@***.***>于2023年5月5日 周五14:47写道：

**Comment by imClumsyPanda** [comment]
已在新版本中修复
