### ISSUE TITLE
[BUG] similarity_search_with_score_by_vector函数返回多个doc时的score结果错误

### ISSUE THREAD

**Issue by wciq1208** [imClumsyPanda/langchain-ChatGLM#252]
**问题描述 / Problem Description**
similarity_search_with_score_by_vector函数返回多个doc时的score结果错误，即所有docs的scores共用了同个结果

**复现问题的步骤 / Steps to Reproduce**
1. vector_store.similarity_search_with_score(query, k=self.top_k) 执行下断点
2. 知识库问答正常发送消息
3. 观察related_docs_with_score

**预期的结果 / Expected Result**
返回的每个doc都应该有不同的score

**实际结果 / Actual Result**
所有doc的score都相同

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：master分支
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）： GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:MACOS
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
此处不应该用j
![665da26e-da5e-48c1-b9f3-a7360976d02a](https://user-images.githubusercontent.com/8669055/236593994-0fb1f90d-aa43-4ce6-9f2c-65cbf89bc8a4.jpeg)
![3705b4d2-1791-4100-b3a2-b3119f543c24](https://user-images.githubusercontent.com/8669055/236594023-2391c376-4dd5-47f0-a064-17fb26553556.jpeg)

**Comment by imClumsyPanda** [comment]
收到，已记录这一bug，将在近期完成修复

⑨个床位不锈钢 ***@***.***>于2023年5月6日 周六10:33写道：

**Comment by imClumsyPanda** [comment]
已在最新版中修复
