### ISSUE TITLE
修改哪里的代码，可以再cpu上跑？

### ISSUE THREAD

**Issue by cristianohello** [imClumsyPanda/langchain-ChatGLM#258]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by xx-zhang** [comment]
什么都不用改，就可以在cpu上跑，但是需要修改 `configs/model_config.py` 文件下的  `LLM_MODEL="chatglm-6b-int4"`

注意内存至少32g; 不然吐字太慢了。

**Comment by ccartermices** [comment]
我按照这个方法做了，但是打开webui.py的时候报错了：
(E:\minconda_extra_env_folder\langchain-chatGLM) E:\langchain-ChatGLM-master>python webui.py
INFO  2023-05-26 08:44:41,965-1d:
loading model config
llm device: cpu
embedding device: cpu
dir: E:\langchain-ChatGLM-master
flagging username: 9eb100c63c814bd98f493513ce26a92f

Downloading (…)lve/main/config.json: 100%|█████████████████████████████████████████████| 838/838 [00:00<00:00, 414kB/s]Downloading (…)iguration_chatglm.py: 100%|████████████████████████████████████████| 4.38k/4.38k [00:00<00:00, 1.46MB/s]A new version of the following files was downloaded from https://huggingface.co/THUDM/chatglm-6b-int4:
- configuration_chatglm.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
Loading THUDM/chatglm-6b-int4...
...
SystemError: 8bit 模型需要 CUDA 支持，或者改用量化后模型！

**Comment by HarveyPhoenix** [comment]
我按照改了下面的参数，但是还是报错了`SystemError: 8bit 模型需要 CUDA 支持，或者改用量化后模型！`
```
EMBEDDING_DEVICE = "cpu"
LLM_DEVICE = "cpu"
LLM_MODEL = "chatglm-6b-int4"
```

**Comment by glide-the** [comment]
dev分支 已修复
