### ISSUE TITLE
ModuleNotFoundError: No module named 'modelscope'

### ISSUE THREAD

**Issue by gedehua** [imClumsyPanda/langchain-ChatGLM#266]
![image](https://user-images.githubusercontent.com/84606552/236675832-c899e396-1f79-43e1-b5ef-cd88c2e8d6a1.png)

**Comment by answerMA** [comment]
https://developer.aliyun.com/article/1023567


安装这个

**Comment by imClumsyPanda** [comment]
如果不需要使用模型分句，可以把textsplitter/__init__.py第二行注释了，这一问题尽量在下一版本完成修复

Ruiming Ma ***@***.***>于2023年5月8日 周一10:09写道：

**Comment by imClumsyPanda** [comment]
已在新版中修复该问题
