### ISSUE TITLE
有兴趣交流本项目应用的朋友可以加一下微信群

### ISSUE THREAD

**Issue by imClumsyPanda** [imClumsyPanda/langchain-ChatGLM#27]
![IMG_1630](https://user-images.githubusercontent.com/5668498/230533162-8b9bfcdd-249c-4efe-b066-4f9ba2ce9f23.jpeg)

**Comment by jiawei243** [comment]
交流群超过200人了，可以加下微信吗？

**Comment by imClumsyPanda** [comment]
@jiawei243 README的二维码已更新，可以加好友了

**Comment by Hagtaril** [comment]
> @jiawei243 README的二维码已更新，可以加好友了

被加好友太频繁，被限制向你发出好友申请了QwQ

**Comment by zhaoyiCC** [comment]
求加好友拉进群，我的微信是Sisily_zy

**Comment by imClumsyPanda** [comment]
请扫描readme底部二维码

yi zhao ***@***.***>于2023年5月4日 周四18:45写道：

**Comment by CLANNADHH** [comment]
同求开新群。感谢大佬们
