### ISSUE TITLE
Logger._log() got an unexpected keyword argument 'end'

### ISSUE THREAD

**Issue by hiber-niu** [imClumsyPanda/langchain-ChatGLM#295]
使用cli_demo的时候，加载一个普通txt文件，输入问题后，报错：“TypeError: Logger._log() got an unexpected keyword argument 'end'”

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8053370/ee498be4-118b-4cbf-9f7c-90f415835dc1)

**Comment by oushu1zhangxiangxuan1** [comment]
对应的修复已经提PR https://github.com/imClumsyPanda/langchain-ChatGLM/pull/297

**Comment by chenkang404** [comment]
同样的问题，一样的报错

**Comment by wxl96** [comment]
logger bug 貌似因为PR #302 又一次出现了
