### ISSUE TITLE
[BUG] 请问可以解释下这个FAISS.similarity_search_with_score_by_vector = similarity_search_with_score_by_vector的目的吗

### ISSUE THREAD

**Issue by Flywolfs** [imClumsyPanda/langchain-ChatGLM#296]
我不太明白这个库自己写的similarity_search_with_score_by_vector方法做的事情，因为langchain原版的similarity_search_with_score_by_vector只是search faiss之后把返回的topk句子组合起来。我觉得原版理解起来没什么问题，但是这个库里自己写的我就没太看明白多做了什么其他的事情，因为没有注释。

并且在经过测试后发现，新版本的similarity_search_with_score_by_vector跑出来的结果和query并不是很相似，反而是原版的结果比较好。可以看下面的截图，第一个是用该库中的similarity_search_with_score_by_vector跑出来的，可以看到”出处“和原本query相似度并不大；第二个截图是关闭了该库的similarity_search_with_score_by_vector，而用langchain原版的，就可以看出”出处“个原本query还是比前一个图更相似的。并且，通过截图可以发现，我设置了topk=6，但是用该库的similarity_search_with_score_by_vector之后，topk失效了，返回了4个document。原版是返回的6个。

query: 中华人民共和国民法典通过日期

Pic1：
<img width="1321" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/10992547/ba463944-3ab8-4a2d-b202-3edae39dda11">

Pic2:
<img width="1321" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/10992547/4cfb53a1-5fa3-433b-9789-ceb33fa7547b">

**Comment by imClumsyPanda** [comment]
目前的考虑是分句方式需要与search返回的上下文方式配合使用，以达到最佳效果。

因此在使用目前项目中默认的chinese_text_splitter分句时，分句一般按照句号、叹号、问号等符号进行划分完整句子，当长度过长时会考虑使用逗号等切分。这样切分的目的是为了让分句后的文段在向量化过程中不会有过多的信息丢失。

但也因为分句方式比较细，导致直接将匹配出的文段结果返回，会文段过段，不一定包含完整关键信息的情况，因此在匹配完成后，依据匹配句子的所在位置，将前后文内容补充进要提供给prompt的context。

假设匹配出的句子是原文中的第2句和第5句，那么扩充可能就会变成1-4句和4-6句，针对可能文段重复的问题，且考虑到文段按照先后顺序可能更有助于理解，有进行了扩充后句子id的顺序排序与去重复，所以返回的文段个数会小于等于top-k。

具体过程可以参考README中文档处理角度的实现流程图。

**Comment by imClumsyPanda** [comment]
在接下来的工作中，会将召回扩充部分与向量库类拆分，并与textsplitter配对使用。

**Comment by Flywolfs** [comment]
> 

谢谢，理解了~

**Comment by TJJ120635** [comment]
求问使用 FAISS 比起 LangChain 官方示例的 Chroma 会更好吗

**Comment by alexhmyang** [comment]
> 目前的考虑是分句方式需要与search返回的上下文方式配合使用，以达到最佳效果。
> 
> 因此在使用目前项目中默认的chinese_text_splitter分句时，分句一般按照句号、叹号、问号等符号进行划分完整句子，当长度过长时会考虑使用逗号等切分。这样切分的目的是为了让分句后的文段在向量化过程中不会有过多的信息丢失。
> 
> 但也因为分句方式比较细，导致直接将匹配出的文段结果返回，会文段过段，不一定包含完整关键信息的情况，因此在匹配完成后，依据匹配句子的所在位置，将前后文内容补充进要提供给prompt的context。
> 
> 假设匹配出的句子是原文中的第2句和第5句，那么扩充可能就会变成1-4句和4-6句，针对可能文段重复的问题，且考虑到文段按照先后顺序可能更有助于理解，有进行了扩充后句子id的顺序排序与去重复，所以返回的文段个数会小于等于top-k。
> 
> 具体过程可以参考README中文档处理角度的实现流程图。

所以经过这些优化之后 解决了 题主的问题了么？ 他说的 原版更好 还是 现在优化之后 的好？

**Comment by yo-WASSUP** [comment]
您好，请问怎么改成langchain原版的similarity_search_with_score_by_vector呢
