### ISSUE TITLE
当前的运行环境是什么，windows还是Linux

### ISSUE THREAD

**Issue by yangliangguang** [imClumsyPanda/langchain-ChatGLM#3]
当前的运行环境是什么，windows还是Linux，python是什么版本？

**Comment by imClumsyPanda** [comment]
@yangliangguang 在Windows和macOS环境下测试可行，macOS中使用时需要把chatglm_llm.py中.half().cuda()修改为.float().to(“mps”)

测试环境python版本为3.8，已知在3.11环境中安装时会遇到部分依赖包无法安装的情况
