### ISSUE TITLE
爲啥最後還是報錯 哭。。

### ISSUE THREAD

**Issue by ZnOKelvin** [imClumsyPanda/langchain-ChatGLM#30]
Failed to import transformers.models.t5.configuration_t5 because of the following error (look up to see
its traceback):
Failed to import transformers.onnx.config because of the following error (look up to see its traceback):
DLL load failed while importing _imaging: 找不到指定的模块。

**Comment by imClumsyPanda** [comment]
建议重装 Python 包 pillow 测试一下

**Comment by ZnOKelvin** [comment]
真的有用~

**Comment by ZnOKelvin** [comment]
然後 剛剛問了一個 問題又報錯了。。。心好累~~~
AttributeError: 'Logger' object has no attribute 'warning_once'

**Comment by ZnOKelvin** [comment]
No sentence-transformers model found with name C:\Users\ziwuadmin/.cache\torch\sentence_transformers\GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
Input your question 请输入问题：hi
D:\Soft_ware\Anaconda\envs\pytorch\lib\site-packages\langchain\chains\conversational_retrieval\base.py:191: UserWarning: `ChatVectorDBChain` is deprecated - please use `from langchain.chains import ConversationalRetrievalChain`
  warnings.warn(

**Comment by imClumsyPanda** [comment]
> No sentence-transformers model found with name C:\Users\ziwuadmin/.cache\torch\sentence_transformers\GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
> Input your question 请输入问题：hi
> D:\Soft_ware\Anaconda\envs\pytorch\lib\site-packages\langchain\chains\conversational_retrieval\base.py:191: UserWarning: `ChatVectorDBChain` is deprecated - please use `from langchain.chains import ConversationalRetrievalChain`
> warnings.warn(

这些都是测试中会出现的warning信息，可以找找看logger版本问题

**Comment by liangtongt** [comment]
pip install transformers==4.27.1 可解决

**Comment by imClumsyPanda** [comment]
> pip install transformers==4.27.1 可解决

已在 requirements.txt 中增加约束
