### ISSUE TITLE
对话到第二次的时候就报错UnicodeDecodeError: 'utf-8' codec can't decode

### ISSUE THREAD

**Issue by ywancit** [imClumsyPanda/langchain-ChatGLM#31]
对话第一次是没问题的，模型返回输出后又给到请输入你的问题，我再输入问题就报错 
File "/root/--2023/mon_Apr/langchain-ChatGLM/knowledge_based_chatglm.py", line 73, in <module>
    query = input("Input your question 请输入问题：")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 3: invalid continuation byte
请问这是什么问题呢？

**Comment by imClumsyPanda** [comment]
推测可能是输入文档中包括特殊字符，无法使用utf8进行解析的原因，可以检查一下文档中是否包含特殊字符

**Comment by ywancit** [comment]
> 

我的文档是一个txt，一行文字描述，然后回车换行，接续第二行文字描述，是因为不可以用回车换行吗？

**Comment by ywancit** [comment]
> 推测可能是输入文档中包括特殊字符，无法使用utf8进行解析的原因，可以检查一下文档中是否包含特殊字符，或者换一份文档测试。


我的文档是一个txt，一行文字描述，然后回车换行，接续第二行文字描述，是因为不可以用回车换行吗？

**Comment by ywancit** [comment]
> 推测可能是输入文档中包括特殊字符，无法使用utf8进行解析的原因，可以检查一下文档中是否包含特殊字符，或者换一份文档测试。

我测试了发现如果第2次提问和第1次完全重复则不会报错，如果换一个新问题就会报错，哪怕只是改一个字 （文档里面确实只有汉字和空格，没有特殊字符）

**Comment by ywancit** [comment]
弄清楚了 是在命令行输入问题的时候不能输入任何退格
第2次提问和第1次完全重复不会报错是因为我是复制过来的，改一个字报错则是因为我退格删了之前的字
