### ISSUE TITLE
[BUG] Windows下上传中文文件名文件，faiss无法生成向量数据库文件

### ISSUE THREAD

**Issue by zfanswer** [imClumsyPanda/langchain-ChatGLM#318]
**问题描述 / Problem Description**
使用cli_demo.py，再windows cmd终端中，给定一个文件地址（文件名是中文）
会出现如下报错。
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/1787565/854f33c7-6969-49fe-bcc4-87a77266b929)

上传的文件改成英文名称后不报错可以正常使用。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.1.11
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese 
- 操作系统及版本 / Operating system and version: windows 11
- Python 版本 / Python version: python 3.8.16
- 其他相关环境信息 / Other relevant environment information: faiss-cpu

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zluckymn** [comment]
求教 windows 上非docker 怎么部署成功的，一直出现一个C++ 的库问题，目前 只能在wsl2中 实现

**Comment by zfanswer** [comment]
后来页面追加了place holder了说明不支持中文，这个先关了。
