### ISSUE TITLE
内网部署时网页无法加载，能否增加离线静态资源

### ISSUE THREAD

**Issue by sanmaomashi** [imClumsyPanda/langchain-ChatGLM#326]
内网部署时网页无法加载，能否增加离线静态资源
网页报错failed to load resource : net ::err_name_not_resolved

**Comment by imClumsyPanda** [comment]
请问是使用webui还是vue前端

三猫码士 ***@***.***>于2023年5月12日 周五10:40写道：

**Comment by Martinfeng** [comment]
可以参考这个：https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10024 来修改Gradio调用本地配置，修改webui.py中的相应代码：`gr.Blocks(css=block_css, theme=gr.themes.Default(**default_font_params))`

**Comment by sanmaomashi** [comment]
@imClumsyPanda 使用的webui

**Comment by imClumsyPanda** [comment]
已按照 @Martinfeng 提到的方法修复该问题
