### ISSUE TITLE
使用colab运行，python3.9，提示包导入有问题

### ISSUE THREAD

**Issue by erikdang** [imClumsyPanda/langchain-ChatGLM#34]
from ._util import is_directory, is_path
ImportError: cannot import name 'is_directory' from 'PIL._util' (/usr/local/lib/python3.9/dist-packages/PIL/_util.py)

另外跑的时候因为显存问题用了init4

**Comment by imClumsyPanda** [comment]
请问这是具体运行代码中哪个部分时遇到的问题？

**Comment by erikdang** [comment]
应该是环境错乱了，重装了使用python3.8解决

**Comment by xiaoyi001yeye** [comment]
> 应该是环境错乱了，重装了使用python3.8解决
麻烦问下colab如何切换python到3.8
