### ISSUE TITLE
弄了个交流群，自己弄好多细节不会，大家技术讨论 加connection-image 我来拉你

### ISSUE THREAD

**Issue by yyx20202020** [imClumsyPanda/langchain-ChatGLM#36]
自己搞好多不清楚的，一起来弄吧。。准备搞个部署问题的解决文档出来

**Comment by yyx20202020** [comment]
VX: connection-image   备注：GPT知识库

**Comment by imClumsyPanda** [comment]
已经有一个项目群了 可以看一下 https://github.com/imClumsyPanda/langchain-ChatGLM/issues/27

**Comment by tenggangren** [comment]
新增清理显存机制，不起作用啊，搞几次就溢出了
