### ISSUE TITLE
我想把文件字符的编码格式改为encoding='utf-8'在哪修改呢，因为会有ascii codec can't decode byte报错

### ISSUE THREAD

**Issue by Mr-IT007** [imClumsyPanda/langchain-ChatGLM#360]
上传中文的txt文件时报错，编码格式为utf-8

报错信息：ascii codec can't decode byte ......

可以自己修改编码格式吗

**Comment by cutelitchi** [comment]
同样遇到，必须重启后才能解决

**Comment by imClumsyPanda** [comment]
目前的处理方式应该需要重写个chinese_text_loader或者在langchain代码里改


xiaoshan ***@***.***>于2023年5月16日 周二13:55写道：

**Comment by wjlszhang** [comment]
改好这个bug了吗？

**Comment by imClumsyPanda** [comment]
已修复

**Comment by RainAutumnZero** [comment]
上传中文的csv文件时报错，编码格式为utf-8，请问如何修改编码格式？
