### ISSUE TITLE
Batches的进度条是在哪里设置的?能否关闭显示?

### ISSUE THREAD

**Issue by doublegssc** [imClumsyPanda/langchain-ChatGLM#366]
使用cli_demo.py进行命令行测试时,每句回答前都有个Batches的进度条
请问这个语句在哪?找了一圈找不到,想关闭其显示

**Comment by liwenju0** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/16049564/07febed7-35e4-405b-86b0-483972cbda42)
这里的show_progress_bar设为False

**Comment by doublegssc** [comment]
可以了,太感谢了 @liwenju0
