### ISSUE TITLE
加载PDF文件时，出现 unsupported colorspace for 'png'

### ISSUE THREAD

**Issue by wmr484** [imClumsyPanda/langchain-ChatGLM#381]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
加载PDF文件时，出现ERROR 2023-05-16 18:00:07,209-1d: unsupported colorspace for 'png'

**复现问题的步骤 / Steps to Reproduce**
python cli.py start cli， 输入PDF文件所在的路径
webui 上传知识库时，后台日志也是显示同样的错误信息

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
ERROR 2023-05-16 18:00:07,209-1d: unsupported colorspace for 'png'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- May 16 5:00pm pull origin/master, 
- 
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): NO
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: Ubuntu 20.04
- Python 版本 / Python version: 3.8
- 其他相关环境信息 / Other relevant environment information:
- Cuda 11.7, A6000 Nvidia
- nvcc:
-  NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by jackgo2080** [comment]
我也遇到了这个问题

**Comment by alexhmyang** [comment]
> 我也遇到了这个问题

俺也一样，有些pdf会报这个错，有些不会

**Comment by imClumsyPanda** [comment]
可以参考一下 https://github.com/imClumsyPanda/langchain-ChatGLM/issues/409#issuecomment-1555425858 看能不能解决

**Comment by imClumsyPanda** [comment]
已按照 https://github.com/imClumsyPanda/langchain-ChatGLM/issues/409#issuecomment-1555425858 修复
