### ISSUE TITLE
'ascii' codec can't encode characters in position 14-44: ordinal not in range(128) 经典bug

### ISSUE THREAD

**Issue by wujiekd** [imClumsyPanda/langchain-ChatGLM#382]
添加了知识库之后进行对话，之后再新增知识库就会出现这个问题。
'ascii' codec can't encode characters in position 14-44: ordinal not in range(128)

如果是一直新增知识库，没有对话是可以新增上去的。

Langchain读取测试了很多次都是没问题的，这里是和啥有关系呢。

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/49955700/d57d84ac-27ef-4138-b999-3f44872dfccf)

**Comment by jiangfangfangxm** [comment]
我也一样，先对话，然后加载知识库，一个简单的.txt文件。报错：ERROR 2023-05-17 05:31:34,438-1d: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)。
我以为是 编码问题，就把文本以ansi格式存贮了，也没有解决问题。报同样的错。

**Comment by wujiekd** [comment]
> 我也一样，先对话，然后加载知识库，一个简单的.txt文件。报错：ERROR 2023-05-17 05:31:34,438-1d: 'ascii' codec can't decode byte 0xe9 in position 0: ordinal not in range(128)。 我以为是编码问题，就把文档以ansi格式存在了，也没有解决问题。报同样的错误。

是的，目前还没解决，尝试从langchain源码进行修改看看

**Comment by wujiekd** [comment]
已经解决，两个地方：

1、首先针对txt进行更改编码方式
if filepath.lower().endswith(".txt"):
            # 检测文件编码
            with open(filepath, 'rb') as f:
                result = chardet.detect(f.read())
            print(result['encoding'])
            # 如果文件编码不是UTF-8，则将其转换为UTF-8
            if result['encoding'] != 'utf-8':
                file_utf8 = filepath.split('.txt')[0]+'_utf8.txt'
                try:
                    with codecs.open(file_utf8, 'w', encoding='utf-8') as f:
                        with codecs.open(filepath, 'r', encoding=result['encoding']) as f2:
                            f.write(f2.read())

                        filepath = file_utf8
                except Exception as e:
                    print('转换文件编码时出现错误：', e)
            else:
                print('文件编码已经是UTF-8,无需转换。')
        from langchain.document_loaders import UnstructuredFileLoader

        loader = UnstructuredFileLoader(filepath, mode="elements")
        textsplitter = ChineseTextSplitter(pdf=False, sentence_size=sentence_size)
        docs = loader.load_and_split(text_splitter=textsplitter)

2、其次更新write_check_file函数
def write_check_file(filepath, docs):
    folder_path = os.path.join(os.path.dirname(filepath), "tmp_files")
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    fp = os.path.join(folder_path, 'load_file.txt')
    with open(fp, 'a+', encoding='utf-8') as fout:
        fout.write("filepath=%s,len=%s" % (filepath, len(docs)))
        fout.write('\n')
        for i in docs:
            fout.write(str(i))
            fout.write('\n')
        fout.close()
    # fp = os.path.join(folder_path, 'load_file.txt')
    # fout = open(fp, 'a')
    # fout.write("filepath=%s,len=%s" % (filepath, len(docs)))
    # fout.write('\n')
    # for i in docs:
    #     fout.write(str(i))
    #     fout.write('\n')
    # fout.close()

**Comment by Oas7pOo** [comment]
> 

大佬请问一下这个是改的哪个文件什么部分啊

**Comment by wujiekd** [comment]
> > 
> 
> 大佬请问一下这个是改的哪个文件什么部分啊

修改这个文件里面的两个模块
langchain-ChatGLM/chains/local_doc_qa.py

**Comment by jiangfangfangxm** [comment]
我根据你的建议，改了两个地方，仍然报错：
修改的第一函数：
def load_file(filepath, sentence_size=SENTENCE_SIZE):
    if filepath.lower().endswith(".md"):
        loader = UnstructuredFileLoader(filepath, mode="elements")
        docs = loader.load()
    elif filepath.lower().endswith(".pdf"):
        loader = UnstructuredPaddlePDFLoader(filepath)
        textsplitter = ChineseTextSplitter(pdf=True, sentence_size=sentence_size)
        docs = loader.load_and_split(textsplitter)
    elif filepath.lower().endswith(".jpg") or filepath.lower().endswith(".png"):
        loader = UnstructuredPaddleImageLoader(filepath, mode="elements")
        textsplitter = ChineseTextSplitter(pdf=False, sentence_size=sentence_size)
        docs = loader.load_and_split(text_splitter=textsplitter)
    elif filepath.lower().endswith(".txt"):
        # 检测文件编码
        with open(filepath, 'rb') as f:
            result = chardet.detect(f.read())
        print(result['encoding'])
        # 如果文件编码不是UTF-8，则将其转换为UTF-8
        if result['encoding'] != 'utf-8':
            file_utf8 = filepath.split('.txt')[0]+'_utf8.txt'
            try:
                with codecs.open(file_utf8, 'w', encoding='utf-8') as f:
                    with codecs.open(filepath, 'r', encoding=result['encoding']) as f2:
                        f.write(f2.read())

                    filepath = file_utf8
            except Exception as e:
                print('转换文件编码时出现错误：', e)
        else:
            print('文件编码已经是UTF-8,无需转换。')
        #from langchain.document_loaders import UnstructuredFileLoader

        loader = UnstructuredFileLoader(filepath, mode="elements")
        textsplitter = ChineseTextSplitter(pdf=False, sentence_size=sentence_size)
        docs = loader.load_and_split(text_splitter=textsplitter)
    else:
        loader = UnstructuredFileLoader(filepath, mode="elements")
        textsplitter = ChineseTextSplitter(pdf=False, sentence_size=sentence_size)
        docs = loader.load_and_split(text_splitter=textsplitter)
    write_check_file(filepath, docs)
    return docs

修改的第二个函数：
def write_check_file(filepath, docs):
    folder_path = os.path.join(os.path.dirname(filepath), "tmp_files")
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)

    fp = os.path.join(folder_path, 'load_file.txt')
    with open(fp, 'a+', encoding='utf-8') as fout:
        fout.write("filepath=%s,len=%s" % (filepath, len(docs)))
        fout.write('\n')
        for i in docs:
            fout.write(str(i))
            fout.write('\n')
        fout.close()
    # fp = os.path.join(folder_path, 'load_file.txt')
    # fout = open(fp, 'a')
    # fout.write("filepath=%s,len=%s" % (filepath, len(docs)))
    # fout.write('\n')
    # for i in docs:
    #     fout.write(str(i))
    #     fout.write('\n')
    # fout.close()
    
运行日志：
utf-8
文件编码已经是UTF-8,无需转换。
ERROR 2023-05-18 23:14:06,709-1d: 'ascii' codec can't decode byte 0xe5 in position 4: ordinal not in range(128)

**Comment by BUPTccy** [comment]
> pip3 install unstructured-inference==0.4.2 unstructured==0.6.1 -i https://mirrors.cloud.tencent.com/pypi/simple
> 
> 执行下,重启就好了.

重装版本后还需要重写代码嘛 大佬

**Comment by wengieeee** [comment]
> pip3 install unstructured-inference==0.4.2 unstructured==0.6.1 -i https://mirrors.cloud.tencent.com/pypi/simple

大佬，我试了一下，没能生效

**Comment by ray-008** [comment]
>  ...
>                     with codecs.open(file_utf8, 'w', encoding='utf-8') as f:
>                         with codecs.open(filepath, 'r', encoding=result['encoding']) as f2:
>                             f.write(f2.read())
> ...

这里读取原始文件时候，建议加上 `errors='ignore'`，有些编码文件调用read方法时还是会报错的

with codecs.open(filepath, 'r', encoding=result['encoding'], errors='ignore') as f2:
