### ISSUE TITLE
微信群人数超过200了，扫码进不去了，群主可以再创建一个新群吗

### ISSUE THREAD

**Issue by xiaochaich** [imClumsyPanda/langchain-ChatGLM#391]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by imClumsyPanda** [comment]
可能是页面缓存问题，上午应该已经更新二维码了，可以到根目录img/qr_code_19看一下
