### ISSUE TITLE
TypeError: 'ListDocsResponse' object is not subscriptable

### ISSUE THREAD

**Issue by Wohoholo** [imClumsyPanda/langchain-ChatGLM#393]
https://github.com/imClumsyPanda/langchain-ChatGLM/blob/a5417e1cf56ca6754cbdfe629afb282ee4bbf48a/api.py#LL189C25-L189C29

应该是用remain_docs.code和remain_docs.data吧？吗？

**Comment by Wohoholo** [comment]
而且应该不是code != 0 而是 200，因为里面的response类 code=200为正常返回

**Comment by PCYTeddy** [comment]
删除文件夹的时候没问题，但删除文件会报错'ListDocsResponse' object is not subscriptable ，按照Wohoholo老师说的修改，成功解决问题！非常感谢，好人一生平安！
