### ISSUE TITLE
请问这是在CLM基础上运行吗？

### ISSUE THREAD

**Issue by diyyong** [imClumsyPanda/langchain-ChatGLM#4]
请问是不是需要本地安装好clm并正常运行的情况下，再按文中的步骤执行才能运行起来？

**Comment by imClumsyPanda** [comment]
Windows联网环境下直接运行就行macOS或未联网需要提前下载好模型，并把embedding和llm模型的model_name参数值都修改为本地路径

**Comment by diyyong** [comment]
十分感谢
