### ISSUE TITLE
mac 加载模型失败

### ISSUE THREAD

**Issue by mrb957600057** [imClumsyPanda/langchain-ChatGLM#417]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
ERROR 2023-05-20 00:40:51,615-1d: Unknown platform: darwin

点击加载模型会报这个错误

**Comment by imClumsyPanda** [comment]
mac暂不支持自动下载transformers模型，需要先手动完成embedding和llm模型下载，具体方法可以参考readme常见问题
