### ISSUE TITLE
上传文件后出现 ERROR __init__() got an unexpected keyword argument 'autodetect_encoding'

### ISSUE THREAD

**Issue by javabloger** [imClumsyPanda/langchain-ChatGLM#428]
上传文件后出现这个问题：ERROR 2023-05-22 11:46:19,568-1d: __init__() got an unexpected keyword argument 'autodetect_encoding'

这是什么原因造成的呢？

**Comment by imClumsyPanda** [comment]
请按照requirements检查一下python包是否满足版本要求

StoneDT-思通数科 ***@***.***>于2023年5月22日 周一11:48写道：

**Comment by javabloger** [comment]
根据 requirements.txt 文件安装的，并且安装成功没有出现问题。
@imClumsyPanda  您是否可以提供一份 txt 格式的知识库文件样本，多谢了。

**Comment by imClumsyPanda** [comment]
content/sample路径中有可用于测试的样例文件

StoneDT-思通数科 ***@***.***>于2023年5月22日 周一12:44写道：

**Comment by javabloger** [comment]
OK，感谢

**Comment by nightyk** [comment]
@你是怎么解决的

**Comment by WellTung666** [comment]
遇到同样的问题，请问怎么解决呢？感谢~

**Comment by imClumsyPanda** [comment]
按照requirements版本要求更新langchain，如果提示找不到对应langchain版本就切换一下pypi源

**Comment by WellTung666** [comment]
> 按照requirements版本要求更新langchain，如果提示找不到对应langchain版本就切换一下pypi源

已经解决，谢谢~

**Comment by offbye** [comment]
安装 pip install langchain==0.0.174
解决了
