### ISSUE TITLE
想问下README中用到的流程图用什么软件画的

### ISSUE THREAD

**Issue by Magicen0722** [imClumsyPanda/langchain-ChatGLM#431]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.
似乎可定制化很强

**Comment by imClumsyPanda** [comment]
draw.io

Magicen0722 ***@***.***>于2023年5月22日 周一17:50写道：
