### ISSUE TITLE
[FEATURE] bing是必须的么？

### ISSUE THREAD

**Issue by ucas010** [imClumsyPanda/langchain-ChatGLM#437]

**Comment by ucas010** [comment]
从这个[脚步](https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/configs/model_config.py#L129)里面发现需要申请bing api，如果不申请，纯用模型推理不可吗？

**Comment by wdkrdem** [comment]
可以

**Comment by imClumsyPanda** [comment]
非必需 可以只用模型
