### ISSUE TITLE
同一台环境下部署了5.22号更新的langchain-chatglm v0.1.13和之前的版本，回复速度明显变慢

### ISSUE THREAD

**Issue by wdkrdem** [imClumsyPanda/langchain-ChatGLM#442]
新langchain-chatglm v0.1.13版本速度很慢

**Comment by jason7323** [comment]
同问题，确实比上一个版本慢不少

**Comment by jethand** [comment]
+1，求fix

**Comment by zhubao315** [comment]
+1

**Comment by wangts108** [comment]
虽然之前没有运行过，但是感觉这个版本比较慢，如果实现流式得输出，整个会不会体验更好

**Comment by liunux4odoo** [comment]
同样的问题，22日更新后，int8流式输出至少慢了一半

**Comment by wangyuwei92** [comment]
速度慢了很多

**Comment by liuchaofei** [comment]
慢死了

**Comment by imClumsyPanda** [comment]
已更新代码，可以测试一下是否恢复到之前的输出速度。

**Comment by liunux4odoo** [comment]
> 已更新代码，可以测试一下是否恢复到之前的输出速度。

刚刚测试过了，速度已经恢复正常。感谢！

**Comment by wujianming1996** [comment]
大佬能不能说下优化了那段代码，想学习下😜

**Comment by imClumsyPanda** [comment]
@wujianming1996 经测试是显存清理那段的问题，降低了速度且对显存优化效果不太明显。就先把流式输出过程中的清理显存那行注释了。
