### ISSUE TITLE
qa的训练数据格式是如何设置的

### ISSUE THREAD

**Issue by zck573693104** [imClumsyPanda/langchain-ChatGLM#45]

**Comment by imClumsyPanda** [comment]
本项目不是使用微调的方式，所以并不涉及到训练过程。

主要原理是输入文档路径后，读取文本➡️文本分割➡️文本向量化➡️问句向量化➡️在文本向量中匹配出与问句向量最相似的top k个➡️匹配出的文本作为上下文和问题一起添加到prompt中➡️提交给llm生成回答
