### ISSUE TITLE
[BUG] API部署，流式输出的函数，少了个question

### ISSUE THREAD

**Issue by shaolongcai** [imClumsyPanda/langchain-ChatGLM#451]
**问题描述 / Problem Description**
这里是不是少了个quesiton,如果不加，请求时，json的格式就变成 "":"提问"，才可以提交

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/29476298/1c34f7d8-8260-42a7-9952-7732d432fd8c)

**复现问题的步骤 / Steps to Reproduce**
1. 执行 api.py
2.定位到stream_chat；question, history, knowledge_base_id = input_json[""], input_json["history"], input_json["knowledge_base_id"]

**预期的结果 / Expected Result**
json应该为：{"question":"提问"}

**实际结果 / Actual Result**
json为：{"":"提问"}

**Comment by exceedzhang** [comment]
确实是一个问题，我也发现了，修改question之后就可以了

**Comment by imClumsyPanda** [comment]
已在最新版代码中修复该问题 感谢指出

**Comment by exceedzhang** [comment]
测试一下，还是有问题的，服务器端已收到客户端请求，但没有响应出错了，错误如下：
@imClumsyPanda 
<img width="1182" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/4583537/b6bdcca1-a832-428f-a22e-b515a2f78493">

**Comment by cristianohello** [comment]
@exceedzhang 
你的客户端的代码怎么写的？能让我看看吗？感谢

**Comment by cristianohello** [comment]
@shaolongcai 
你的客户端代码是怎么写的？我看下。感谢
