### ISSUE TITLE
项目结构的简洁性保持

### ISSUE THREAD

**Issue by xx-zhang** [imClumsyPanda/langchain-ChatGLM#454]
**功能描述 / Feature Description**
现在项目越来越不简洁了，尝鲜下个版本的就放另外一个分支，我们当前master版就不要有那么多没有用的目录。 。
**解决的问题 / Problem Solved**

**实现建议 / Implementation Suggestions**
比如 views 可以创建一个vue-ui, 比如   lamma 的创建另外一个分支, fastchat要是用不上也不放上去， 还有texstspliter里面的还有个阿里云 要是不能用也不要，要是能用就用transformer改下否则还要额外装一个modscope.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

大佬您觉得有没有道理

**Comment by imClumsyPanda** [comment]
下一版本会先完成部分整合

**Comment by sticktoFE** [comment]
期待，目前存在冗余目录和代码，models模块为了统一个模型调用，变得很重，读起来不容易
