### ISSUE TITLE
项目群扫码进不去了

### ISSUE THREAD

**Issue by mag05270** [imClumsyPanda/langchain-ChatGLM#455]
项目群扫码进不去了，是否可以加一下微信拉我进群，谢谢！微信号：daniel-0527

**Comment by wzdacyl** [comment]
同申请入群，微信号：yaoyuleo

**Comment by mag05270** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by smartheye** [comment]
+1，微信号：heyeibm
谢谢

**Comment by qq460046000** [comment]
+1，微信号：Zhang_zhengao
谢谢

**Comment by hzt12345** [comment]
+1，微信号：Peter98Huang
谢谢

**Comment by imClumsyPanda** [comment]
已在readme中更新qq群二维码。

**Comment by imClumsyPanda** [comment]
已重新增加微信群二维码

**Comment by xuriliuhen** [comment]
微信群又超过200人，加不进去了，求拉微信群
微信号：xuriliuhen
谢谢

**Comment by imClumsyPanda** [comment]
@xuriliuhen 昨晚已经更新readme中二维码

**Comment by xuriliuhen** [comment]
> @xuriliuhen 昨晚已经更新readme中二维码

谢谢谢谢，已进群。

**Comment by s861092982** [comment]
@xuriliuhen 
微信号：learning-2077  帮拉我进群。二维码过期了

**Comment by mag05270** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by imClumsyPanda** [comment]
> @xuriliuhen 微信号：learning-2077 帮拉我进群。二维码过期了

已更新二维码

**Comment by long123524** [comment]
求拉，微信号：lotus131455890

**Comment by mag05270** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
