### ISSUE TITLE
The FileType.UNK file type is not supported in partition. 解决办法

### ISSUE THREAD

**Issue by yaleimeng** [imClumsyPanda/langchain-ChatGLM#46]
ValueError: Invalid file /home/yawu/Documents/langchain-ChatGLM-master/data. The FileType.UNK file type is not supported in partition.
这个报错是因为输入的filepath不正确。demo中需要给一个具体的目录+文件名，而不是文件夹名称。

希望对大家有所帮助。

**Comment by imClumsyPanda** [comment]
2023/04/11 更新后，`knowledge_based_chatglm.py`中增加对输入路径的判断，如果是文件夹路径，则遍历文件夹下文件，全部进行向量化，并提示每个文件是否成功加载；如果是文件路径则直接将该文件加载。
