### ISSUE TITLE
请求拉我入群讨论，海硕一枚，专注于LLM等相关技术 

### ISSUE THREAD

**Issue by BillySen** [imClumsyPanda/langchain-ChatGLM#461]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.
请热心大佬加一下我的微信  lrj244737137  拉我入群交流，感谢！！
**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by qq460046000** [comment]
想进群，求更新一个二维码

**Comment by imClumsyPanda** [comment]
已在readme中更新qq群二维码。

**Comment by imClumsyPanda** [comment]
已重新增加微信群二维码

**Comment by zouheliang2011** [comment]
好像群满了，能拉我进去吗？我准备在本地机器上跑一下。微信号z414859433

**Comment by ihongxx** [comment]
请求拉进群，微信：hxx1078367431

**Comment by imClumsyPanda** [comment]
> 请求拉进群，微信：hxx1078367431

readme中已经更新群聊二维码
