### ISSUE TITLE
如何读取多个txt文档？

### ISSUE THREAD

**Issue by ywancit** [imClumsyPanda/langchain-ChatGLM#47]
如题，请教一下如何读取多个txt文档？示例代码中只给了读一个文档的案例，这个input我换成string之后也只能指定一个文档，无法用通配符指定多个文档，也无法传入多个文件路径的列表。
感谢解答

**Comment by imClumsyPanda** [comment]
2023/04/11 更新后，`knowledge_based_chatglm.py` 中增加对输入路径的判断，如果是文件夹路径，则遍历文件夹下文件，全部进行向量化，并提示每个文件是否成功加载；如果是文件路径则直接将该文件加载。

**Comment by ywancit** [comment]
> 2023/04/11 更新后，`knowledge_based_chatglm.py` 中增加对输入路径的判断，如果是文件夹路径，则遍历文件夹下文件，全部进行向量化，并提示每个文件是否成功加载；如果是文件路径则直接将该文件加载。

Thanks!
