### ISSUE TITLE
RuntimeError: Only Tensors of floating point and complex dtype can require gradients

### ISSUE THREAD

**Issue by jiangbossB** [imClumsyPanda/langchain-ChatGLM#483]
刚更新了最新版本：
env：
device:cpu
model name: chatglm int4 
在loader.py中 没更改之前 抛出了异常 ：raise SystemError("8bit 模型需要 CUDA 支持，或者改用量化后模型！")
然后我就把判断改为： if self.load_in_8bit and not self.llm_device.lower().startswith("cuda"):
最后就是 RuntimeError: Only Tensors of floating point and complex dtype can require gradients 这个异常了 debug后发现是在from_pretrained时出错，但是param：{'low_cpu_mem_usage': True, 'device_map': 'auto', 'trust_remote_code': True, 'torch_dtype': torch.float16} 已经是float16了呀 为什么会报错？先谢过各位大佬

**Comment by jiangbossB** [comment]
已经解决了 params 只用两个参数 {'trust_remote_code': True, 'torch_dtype': torch.float16}

**Comment by k1ng0fic3** [comment]
跪谢，救星！给大佬磕一个

**Comment by luocj** [comment]
这个问题解决了吗，是否已提交了最新版本哦

**Comment by brizer** [comment]
> 已经解决了 params 只用两个参数 {'trust_remote_code': True, 'torch_dtype': torch.float16}

Good Job
