### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'  

### ISSUE THREAD

**Issue by jiangbossB** [imClumsyPanda/langchain-ChatGLM#484]
已经解决了 params 只用两个参数 {'trust_remote_code': True, 'torch_dtype': torch.float16}

_Originally posted by @jiangbossB in https://github.com/imClumsyPanda/langchain-ChatGLM/issues/483#issuecomment-1565945276_

但是使用cpu fp16的精度进行推理 又出现了这样的错误：RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'  没更新代码之前 我也是cpu推理是没有任何问题的

**Comment by jiangbossB** [comment]
在gpu应该不会有这种问题的

**Comment by 33naihe33** [comment]
麻烦问下，在cpu跑出现同样的问题，怎么解决的呀
