### ISSUE TITLE
nltk package unable to either download or load local nltk_data folder

### ISSUE THREAD

**Issue by nameless0704** [imClumsyPanda/langchain-ChatGLM#49]
I'm running this project on an offline Windows Server environment so I download the Punkt and averaged_perceptron_tagger tokenizer in this directory:
`'nltk_data/tokenizers/punkt/english.pickle'` but I keep receiving this LookupError:
```
LookupError:
**********************************************************************
  Resource [93maveraged_perceptron_tagger[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtaggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle[0m

  Searched in:
    - 'C:\\Users\\username/nltk_data'
    - 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python38\\nltk_data'
    - 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python38\\share\\nltk_data'
    - 'C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python38\\lib\\nltk_data'
    - 'C:\\Users\\username\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
**********************************************************************
```
I put the nltk_data file in almost all of the directories above but this error keeps coming up.  How can I solve this on an offline machine?

**Comment by pollymars** [comment]
还要去nltk.org/nltk_data，下载averaged_perceptron_tagger.pickle

**Comment by nameless0704** [comment]
> 还要去nltk.org/nltk_data，下载averaged_perceptron_tagger.pickle

有这个呢，也不行

**Comment by nameless0704** [comment]
仔细看了报错，路径保存错了。整体是这个路径👇
nltk_data
- corpora
- taggers
- - averaged_perceptron_tagger
- - - averaged_perceptron_tagger.pickle
- tokenizers
- - punkt
- - - english.pickle

一开始下punkt的时候不知道taggers要单独的一个文件夹没仔细看报错，感谢。

**Comment by bk007lz** [comment]
> 仔细看了报错，路径保存错了。整体是这个路径👇 nltk_data
> 
> * corpora
> * taggers
> * * averaged_perceptron_tagger
> * * * averaged_perceptron_tagger.pickle
> * tokenizers
> * * punkt
> * * * english.pickle
> 
> 一开始下punkt的时候不知道taggers要单独的一个文件夹没仔细看报错，感谢。

windows下要放在哪个目录下？
