### ISSUE TITLE
[BUG] 文件未成功加载，请重新上传文件

### ISSUE THREAD

**Issue by ucas010** [imClumsyPanda/langchain-ChatGLM#504]
webui.py
多次上传仍旧失败。日志显示
ERROR 2023-05-31 10:28:41,847-1d: [Errno 2] No such file or directory: '/da/langchain-ChatGLM/content/new/tmp_files/tmp.png'
ERROR 2023-05-31 10:28:49,714-1d: [Errno 2] No such file or directory: '/da/langchain-ChatGLM/content/new/tmp_files/tmp.png'
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/50656998/a9aa25c0-88c4-40d0-bfed-f318a143d18e)

**Comment by imClumsyPanda** [comment]
已在最新版代码中修复该问题
