### ISSUE TITLE
[BUG] bug 17 ，pdf和pdf为啥还不一样呢？为啥有的pdf能识别？有的pdf识别不了呢？

### ISSUE THREAD

**Issue by ucas010** [imClumsyPanda/langchain-ChatGLM#506]
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/465#issuecomment-1569433207
bug 17 ，pdf和pdf为啥还不一样呢？为啥有的pdf能识别？有的pdf识别不了呢？
能识别的pdf，举例子2303.14070.pdf
[2303.14070.pdf](https://github.com/imClumsyPanda/langchain-ChatGLM/files/11608226/2303.14070.pdf)
不能识别的pdf，
[测试pdf不能识别.pdf](https://github.com/imClumsyPanda/langchain-ChatGLM/files/11608244/pdf.pdf)
请大佬给出意见，该咋办呢？

**Comment by imClumsyPanda** [comment]
已在最新版代码中修复该问题
