### ISSUE TITLE
在推理的过程中卡住不动，进程无法正常结束

### ISSUE THREAD

**Issue by izhaolinger** [imClumsyPanda/langchain-ChatGLM#516]
**问题描述 / Problem Description**
我在运行cli_demo时，加载了本地的一个txt文件，文件仅20行内容，当我向它提问时，有的问题会导致它在推理的过程中卡住不动了。没有出现报错信息，程序也无法正常结束。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python cli_demo.py
2. 加载成功后，输入一个本地路径
3. 向它提问，输入“python怎么实现冒泡排序”
4. 在输出的过程中卡住不动，程序假死

**预期的结果 / Expected Result**
程序能够正常推理

**实际结果 / Actual Result**
程序无法正常推理，还会假死

**环境信息 / Environment Information**
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ ChatGLM-6B
- 使用的 Embedding 模型text2vec-large-chinese
- 操作系统及版本 / Operating system and version: wsl2 centos7
- Python 版本 / Python version: anaconda python3.10。11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/29848522/93a0102f-1db6-4bad-bf1f-769ea0a02f57)

**Comment by shangzhensen** [comment]
+1

**Comment by izhaolinger** [comment]
通过分析程序源码，发现是在流式输出时，__next__函数中，q.get被阻塞了，但不知道阻塞的原因是什么呢？

**Comment by izhaolinger** [comment]
我之前是在windows11下，通过wsl安装了centos7的环境，出现了这样的问题。

后来我租了一台ubuntu20.04的云服务器，cuda为11.8，python环境为3.8，使用同样的程序与文档能够正常运行。是否是系统的问题呢？

**Comment by imClumsyPanda** [comment]
> 通过分析程序源码，发现是在流式输出时，__next__函数中，q.get被阻塞了，但不知道阻塞的原因是什么呢？

最新版代码中应该已经删掉这部分代码了

**Comment by izhaolinger** [comment]
> > 通过分析程序源码，发现是在流式输出时，__next__函数中，q.get被阻塞了，但不知道阻塞的原因是什么呢？
> 
> 最新版代码中应该已经删掉这部分代码了

我确实发现最新的代码已经有变化了，但在windows中，使用最新的代码后仍然会出现这样的情况。

**Comment by glide-the** [comment]
> > > 通过分析程序源码，发现是在流式输出时，__next__函数中，q.get被阻塞了，但不知道阻塞的原因是什么呢？
> > 
> > 
> > 最新版代码中应该已经删掉这部分代码了
> 
> 我确实发现最新的代码已经有变化了，但在windows中，使用最新的代码后仍然会出现这样的情况。

最新这段代码已经被删除，如果还出现，这个阻塞的问题，您需要检查代码版本了

> 通过分析程序源码，发现是在流式输出时，__next__函数中，q.get被阻塞了，但不知道阻塞的原因是什么呢？

**Comment by izhaolinger** [comment]
> > > > 通过分析程序源码，发现是在流式输出时，__next__函数中，q.get被阻塞了，但不知道阻塞的原因是什么呢？
> > > 
> > > 
> > > 最新版代码中应该已经删掉这部分代码了
> > 
> > 
> > 我确实发现最新的代码已经有变化了，但在windows中，使用最新的代码后仍然会出现这样的情况。
> 
> 最新这段代码已经被删除，如果还出现，这个阻塞的问题，您需要检查代码版本了
> 
> > 通过分析程序源码，发现是在流式输出时，__next__函数中，q.get被阻塞了，但不知道阻塞的原因是什么呢？

好的，谢谢，我再去尝试一下。

**Comment by izhaolinger** [comment]
问题找到了，是pve分配机器时不合理导致的动不动死机。
