### ISSUE TITLE
[FEATURE] 调整模型下载的位置

### ISSUE THREAD

**Issue by zachary-guo** [imClumsyPanda/langchain-ChatGLM#537]
模型默认下载到 $HOME/.cache/huggingface/，当 C 盘空间不足时无法完成模型的下载。configs/model_config.py 中也没有调整模型位置的参数。

能够提供对模型下载位置的配置项？

**Comment by imClumsyPanda** [comment]
按照readme中常见问题，手动下载到本地后在config/model_config的llm_model_dict中修改local_model_path
