### ISSUE TITLE
[BUG] langchain=0.0.174 出错

### ISSUE THREAD

**Issue by iceteacqx** [imClumsyPanda/langchain-ChatGLM#543]
**问题描述 / Problem Description**
运行 pip install -r requirements.txt就出错了
然后我把版本改成  0.0.17
安装成功
但是运行 python loader/image_loader.py
出错
Traceback (most recent call last):
  File "loader/image_loader.py", line 4, in <module>
    from langchain.document_loaders.unstructured import UnstructuredFileLoader
ModuleNotFoundError: No module named 'langchain.document_loaders'
于是我又运行了

pip install "unstructured[local-inference]"
pip install layoutparser[layoutmodels,tesseract]

可依然还是
Traceback (most recent call last):
  File "loader/image_loader.py", line 4, in <module>
    from langchain.document_loaders.unstructured import UnstructuredFileLoader
ModuleNotFoundError: No module named 'langchain.document_loaders'
**复现问题的步骤 / Steps to Reproduce**
pip install -r requirements.txt

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
ERROR: Could not find a version that satisfies the requirement langchain==0.0.174 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27)
ERROR: No matching distribution found for langchain==0.0.174

- 操作系统及版本 / Operating system and version: window 11
- Python 版本 / Python version: 3.8
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by imClumsyPanda** [comment]
看一下readme常见问题最后一条

chenQx ***@***.***>于2023年6月4日 周日11:38写道：

**Comment by iceteacqx** [comment]
pip install -r requirements.txt -i https://pypi.python.org/simple
pip install langchain==0.0.174 -i https://pypi.tuna.tsinghua.edu.cn/simple/
三个都试了还是不行

**Comment by iceteacqx** [comment]
> 
pip install -r requirements.txt -i https://pypi.python.org/simple
pip install langchain==0.0.174 -i https://pypi.tuna.tsinghua.edu.cn/simple/
三个都试了还是不行

**Comment by imClumsyPanda** [comment]
python版本需要在3.8.1及以上

**Comment by iceteacqx** [comment]
好了，但是又有新问题了
python loader/image_loader.py
   from configs.model_config import NLTK_DATA_PATH
ModuleNotFoundError: No module named 'configs'
我也
import nltk
nltk.download()
要怎么搞

> python版本需要在3.8.1及以上

**Comment by imClumsyPanda** [comment]
> 好了，但是又有新问题了 python loader/image_loader.py from configs.model_config import NLTK_DATA_PATH ModuleNotFoundError: No module named 'configs' 我也 import nltk nltk.download() 要怎么搞
> 
> > python版本需要在3.8.1及以上

pip uninstall configs

**Comment by WangYuuuuuuu** [comment]
pip install langchain==0.0.174 -i https://pypi.org/simple，亲测有用
