### ISSUE TITLE
SystemError: 8bit 模型需要 CUDA 支持，或者改用量化后模型！

### ISSUE THREAD

**Issue by fanxiaoyong** [imClumsyPanda/langchain-ChatGLM#550]
docker 部署后,启动docker,过会儿容器会自动退出,logs报错 SystemError: 8bit 模型需要 CUDA 支持，或者改用量化后模型！ [NVIDIA Container Toolkit](https://github.com/NVIDIA/nvidia-container-toolkit) 也已经安装了

**Comment by glide-the** [comment]
尝试检查pytorch环境与cuda版本的兼容列表，在你设备和软件版本都没问题的情况下，一般你只需要配置LD_LIBRARY_PATH环境变量就可以正常运行
如果无法解决CUDA依赖，尝试使用其它方法量化模型
