### ISSUE TITLE
[BUG] 上传知识库超过1M报错

### ISSUE THREAD

**Issue by ywm12345** [imClumsyPanda/langchain-ChatGLM#556]
**问题描述 / Problem Description**
上传知识库超过1M报错

**复现问题的步骤 / Steps to Reproduce**
1.运行webui.py
2.访问地址，上传知识库，知识库大于1M，报错

**Comment by shen5455** [comment]
你不说你的环境 别人怎么复现

**Comment by ywm12345** [comment]
ubuntu20.04  
python3.8 
conda虚拟环境
gradio==3.33.1（可以使用root_path设置反向代理）
master分支代码，修改模型配置，启动webui.py,
![图片](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/85282624/74b854d2-aa6e-488a-ad15-95b22ff97070)
上传大于1M的文件报错

**Comment by ywm12345** [comment]
已解决，nginx代理的问题

**Comment by litongyun233** [comment]
我也遇到同样的问题，请问是如何解决的？如何排查是否是nginx代理的问题？ @ywm12345
