### ISSUE TITLE
[BUG] 响应速度极慢，应从哪里入手优化？48C/128G/8卡

### ISSUE THREAD

**Issue by xenos-code** [imClumsyPanda/langchain-ChatGLM#573]
运行环境：ubuntu20.04
安装过程：解决了找不到CONFIGS目录的问题外，缺一个包，其他顺利。
启动过程：下载模型文件，修改知识库文件路径，多卡运行python webui.py
体验过程：访问正常，默认状态下提问，响应提问约几秒，有明显的卡顿，然后。。。回答问题的响应速度几秒一个字，看资源占用很小
问题：这是一种无法正常使用的状态，应该是不正常的，暂时没有找到配置优化或其他 下手的点

**Comment by ImmNaruto** [comment]
理论上来说你这个配置应该不会太卡，你看下你部署的模型是不是量化之后的，推荐使用FP16加载

**Comment by xenos-code** [comment]
试着运行了一下webui_st.py，提示缺包streamlit,安装包提示和若干依赖包冲突，然后再运行webui.py，速度快了不少，像打字机了。。
