### ISSUE TITLE
如何加载本地的embedding模型（text2vec-large-chinese模型文件）

### ISSUE THREAD

**Issue by BrettLL** [imClumsyPanda/langchain-ChatGLM#582]
因为需要离线部署，所以要把模型放到本地，我修改了chains/local_doc_qa.py中的HuggingFaceEmbeddings()，在其中加了一个cache_folder的参数，保证下载的文件在cache_folder中，model_name是text2vec-large-chinese。如cache_folder='/home/xx/model/text2vec-large-chinese', model_name='text2vec-large-chinese'，这样仍然需要联网下载报错，请问大佬如何解决该问题？

**Comment by czs1993** [comment]
你先从HuggingFace把预训练模型下载到本地，然后再config/model_config.py中配置成本地路径就可以从本地加载了。
```
embedding_model_dict = {
    "ernie-tiny": "xxxx/embedding_model/ernie-3.0-nano-zh",
    "ernie-base": "xxx/embedding_model/ernie-3.0-base-zh",
    "text2vec-base": "xxx/embedding_model/text2vec-base-chinese",
    "text2vec": "xxx/embedding_model/text2vec-large-chinese",
}
```

**Comment by ucas010** [comment]
@czs1993 thanks, will have a try

**Comment by BrettLL** [comment]
@czs1993 yes,it works. thanks~

**Comment by DayDreamChaser** [comment]
行不通啊

**Comment by feidaogoodboy** [comment]
from langchain_huggingface import HuggingFaceEmbeddings
 embed_path = r'F:\bigmodels\BAAI\bge-large-en-v1.5'
 embeddings = HuggingFaceEmbeddings(
      model_name=embed_path,)

就是这么简单
