### ISSUE TITLE
[BUG] raise partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' when call interface `upload_file` 

### ISSUE THREAD

**Issue by hzg0601** [imClumsyPanda/langchain-ChatGLM#591]
**问题描述 / Problem Description**

在环境中按照默认的requirements.txt安装依赖后，发起api.py服务，在调用upload_file接口时，上传.md文件，抛出如下错误：
partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)

**Comment by hzg0601** [comment]
这是由于 charset_normalizer模块版本过高导致的，需要降低低charset_normalizer的版本,测试在charset_normalizer==2.1.0上可用。

**Comment by leoterry-ulrica** [comment]
> 这是由于 charset_normalizer模块版本过高导致的，需要降低低charset_normalizer的版本,测试在charset_normalizer==2.1.0上可用。

没能解决
