### ISSUE TITLE
[BUG] raise OSError: [Errno 101] Network is unreachable when call interface upload_file and upload .pdf files

### ISSUE THREAD

**Issue by hzg0601** [imClumsyPanda/langchain-ChatGLM#592]
**问题描述 / Problem Description**
发起api.py服务，在调用upload_file接口时，上传.pdf文件，抛出如下错误：
OSError: [Errno 101] Network is unreachable

错误详细信息：
HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6f2a6b1a30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by hzg0601** [comment]
某些情况下,linux系统上的ip在请求下载ch_PP-OCRv3_rec_infer.tar等文件时，可能会抛出OSError: [Errno 101] Network is unreachable，此时需要首先修改anaconda3/envs/[虚拟环境名]/lib/[python版本]/site-packages/paddleocr/ppocr/utils/network.py脚本，将57行的

```
download_with_progressbar(url, tmp_path)
```

修改为：

```
        try:
            download_with_progressbar(url, tmp_path)
        except Exception as e:
            print(f"download {url} error,please download it manually:")
            print(e)
```

然后按照给定网址，如"https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_rec_infer.tar"手动下载文件，

然后上传到对应的文件夹中，如“.paddleocr/whl/rec/ch/ch_PP-OCRv3_rec_infer/ch_PP-OCRv3_rec_infer.tar”

**Comment by hzg0601** [comment]
不需要

**Comment by ye7love7** [comment]
另外个issue里说需要，我测试一下，之前似乎没报过这个错



---Original---
From: "Zhi-guo ***@***.***&gt;
Date: Tue, Jul 18, 2023 16:11 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [imClumsyPanda/langchain-ChatGLM] [BUG] raise OSError: [Errno101] Network is unreachable when call interface upload_file and upload .pdffiles (Issue #592)




 
不需要
