### ISSUE TITLE
如果直接用vicuna作为基座大模型，需要修改的地方有哪些？

### ISSUE THREAD

**Issue by cristianohello** [imClumsyPanda/langchain-ChatGLM#596]
vicuna模型有直接转换好的没有？也就是llama转换之后的vicuna。

**Comment by dongyihua543** [comment]
vicuna-13b-hf能用了吗？

**Comment by cristianohello** [comment]
@imClumsyPanda 有直接可以用的vicuna权重吗？

**Comment by Data2Me** [comment]
同问

**Comment by cristianohello** [comment]
@glide-the 
你好，请问，vicuna-13b-hf这个llama转换成功的权重去哪下载？网上有吗？我看了很多，都需要llama结合vicuna-13b-hf转换，有转化好的最终vicuna权重吗？

**Comment by glide-the** [comment]
fastchat的readme中有介绍合并方法，至于权重文件，您需要依靠搜索引擎
