### ISSUE TITLE
[BUG] config 使用  chatyuan  无法启动

### ISSUE THREAD

**Issue by 376924098** [imClumsyPanda/langchain-ChatGLM#604]
"chatyuan": {
        "name": "chatyuan",
        "pretrained_model_name": "ClueAI/ChatYuan-large-v2",
        "local_model_path": "D:\\code\\model\\ChatYuan-large-v2",
        "provides": None
    },

启动报错：TypeError: argument of type 'NoneType' is not iterable

**Comment by hzg0601** [comment]
我有时候都怀疑你们是不是国安局的研究人员，所以报错信息里包含了国家机密，不宜示人。。。。
既不给出调用信息，也不给出模型的输出信息，还不给出完整的错误提示，都靠别人猜去定位错误，冯诺依曼复生了他能解决吗。。。
