### ISSUE TITLE
使用fashchat api之后，后台报错APIError 如图所示

### ISSUE THREAD

**Issue by jwh5566** [imClumsyPanda/langchain-ChatGLM#606]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/7205703/3c42b40d-3946-4675-af6a-294269f75c63)
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/7205703/49202689-bfb6-4edc-8148-ef9557a8513b)

我按照https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/docs/fastchat.md
修改了配置文件，但是还是报错，请问是什么原因呢？？麻烦指点一下 谢谢！

**Comment by tomFoxxxx** [comment]
您好 请问如何解决的
