### ISSUE TITLE
local_doc_qa.py中MyFAISS.from_documents() 这个语句看不太懂。MyFAISS类中没有这个方法，其父类FAISS和VectorStore中也只有from_texts方法[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by jake221** [imClumsyPanda/langchain-ChatGLM#619]
local_doc_qa.py中MyFAISS.from_documents() 这个语句看不太懂。MyFAISS类中没有这个方法，其父类FAISS和VectorStore中也只有from_texts方法

**Comment by hzg0601** [comment]
父类VectorStore是有这个方法的
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/22924096/76ee055d-4536-452d-8233-c677b5c0918f)
