### ISSUE TITLE
[BUG] TypeError: similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'

### ISSUE THREAD

**Issue by hunter2009pf** [imClumsyPanda/langchain-ChatGLM#624]
**问题描述 / Problem Description**
进行向量相似匹配的时候，faiss里的similarity_search_with_score_by_vector()方法报这个，不知道咋弄

**复现问题的步骤 / Steps to Reproduce**
直接python main.py
然后上传一份文件
然后针对文件提问，就报这个错

TypeError: similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'

**Comment by hunter2009pf** [comment]
我安装的是faiss-cpu这个包

**Comment by imClumsyPanda** [comment]
请确认langchain版本是否与requirements中一致

**Comment by hunter2009pf** [comment]
> 请确认langchain版本是否与requirements中一致

果然是langchain版本的问题，感谢大佬！
