### ISSUE TITLE
ChatGLM-6B模型能否回答英文问题？

### ISSUE THREAD

**Issue by CoderBinGe** [imClumsyPanda/langchain-ChatGLM#640]
![question](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/26380524/4ac3daef-f034-489a-ad28-528c13b89ebf)

大佬，请问一下，如果本地知识文档是英文，ChatGLM-6B模型能否回答英文问题？不能的话，有没有替代的模型推荐，期待你的回复，谢谢

**Comment by imClumsyPanda** [comment]
把 configs/model_config 中 prompt_template 修改为英文，且要求模型以英文进行回答。
