### ISSUE TITLE
requirements中langchain版本错误

### ISSUE THREAD

**Issue by Qiuzg** [imClumsyPanda/langchain-ChatGLM#65]
langchain版本应该是0.0.12而不是0.0.120

**Comment by imClumsyPanda** [comment]
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/5668498/231382427-6d94eb71-6c41-4dfd-9668-fd24ec9cf0aa.png">

按照 pypi.org 和各版本测试结果是 0.0.120 及以上版本

**Comment by imClumsyPanda** [comment]
如果使用的pypi源是国内源，可能出现高版本 langchain 未及时添加至 pypi 源的问题

**Comment by smile-II** [comment]
显示没有0.0.120这个版本
ERROR: Could not find a version that satisfies the requirement langchain>=0.0.120 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27)
ERROR: No matching distribution found for langchain>=0.0.120

**Comment by imClumsyPanda** [comment]
@smile-II 请看上一条回复
