### ISSUE TITLE
$ python loader/image_loader.py 运行时报错“ModuleNotFoundError: No module named 'configs'”

### ISSUE THREAD

**Issue by ysyx2008** [imClumsyPanda/langchain-ChatGLM#691]
**问题描述 / Problem Description**
$ python loader/image_loader.py 运行时报错“ModuleNotFoundError: No module named 'configs'”

**复现问题的步骤 / Steps to Reproduce**
1. 参照安装指南执行到最后一步。
2. python loader/image_loader.py
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**

**实际结果 / Actual Result**
(langchain) F:\AI\langchain-ChatGLM>python loader/image_loader.py
Traceback (most recent call last):
  File "F:\AI\langchain-ChatGLM\loader\image_loader.py", line 8, in <module>
    from configs.model_config import NLTK_DATA_PATH
ModuleNotFoundError: No module named 'configs'

**Comment by hzg0601** [comment]
你应该简单了解一下python的文件和目录访问机制

**Comment by ysyx2008** [comment]
也不是完全不懂。。。。
但教程既然这样写了就应该能够顺利执行才对。

**Comment by sylcool** [comment]
我也遇到了同样的问题！！

image_loader.py作为python文件直接执行，也会优先导入包。
```python
from configs.model_config import NLTK_DATA_PATH
nltk.data.path = [NLTK_DATA_PATH] + nltk.data.path
```
以上代码会先被执行。


然后才会执行`if __name__ == "__main__":`内的语句。
```python
if __name__ == "__main__":
    import sys
    sys.path.append(os.path.dirname(os.path.dirname(__file__)))
```
所以把configs加入加载路径的代码就无效了，导致找不到configs模块。

## 解决办法
需要把导入configs的代码，暂时移动到main内，`sys.path.append`语句的后面。
```python
if __name__ == "__main__":
    import sys
    sys.path.append(os.path.dirname(os.path.dirname(__file__)))
    from configs.model_config import NLTK_DATA_PATH
    nltk.data.path = [NLTK_DATA_PATH] + nltk.data.path
```

**Comment by ysyx2008** [comment]
> 我也遇到了同样的问题！！
> 
> image_loader.py作为python文件直接执行，也会优先导入包。
> 
> ```python
> from configs.model_config import NLTK_DATA_PATH
> nltk.data.path = [NLTK_DATA_PATH] + nltk.data.path
> ```
> 
> 以上代码会先被执行。
> 
> 然后才会执行`if __name__ == "__main__":`内的语句。
> 
> ```python
> if __name__ == "__main__":
>     import sys
>     sys.path.append(os.path.dirname(os.path.dirname(__file__)))
> ```
> 
> 所以把configs加入加载路径的代码就无效了，导致找不到configs模块。
> ## 解决办法
> 
> 需要把导入configs的代码，暂时移动到main内，`sys.path.append`语句的后面。
> 
> ```python
> if __name__ == "__main__":
>     import sys
>     sys.path.append(os.path.dirname(os.path.dirname(__file__)))
>     from configs.model_config import NLTK_DATA_PATH
>     nltk.data.path = [NLTK_DATA_PATH] + nltk.data.path
> ```

非常感谢你专业的指导！

**Comment by ysyx2008** [comment]
已有答案，关闭此问题。再次感谢。

**Comment by hkun0120** [comment]
既然我们都会遇到这样的问题，为什么不更新一下github上的安装指南信息呢

**Comment by yyl424525** [comment]
为什么有bug也不改呢？
