### ISSUE TITLE
请问：纯cpu可以吗？

### ISSUE THREAD

**Issue by jiaozn** [imClumsyPanda/langchain-ChatGLM#7]
很酷的实现，极大地开拓了我的眼界！很顺利的在gpu机器上运行了
另：想在另一台cpu的服务器部署（性能还可以），想提前了解：

1、仅CPU可以运行吗？（chatglm可以，但考虑到依赖的其他项目，自己就不确定了）
2、win安装detectron2好像有点困难啊……是否有好经验？（在gpu机器安装时遇到问题，当时偷懒去ubuntu搞定了）

**Comment by imClumsyPanda** [comment]
1. 理论上说是可以的，我在macOS和windows环境都做过测试，测试过程中embedding模型都有试过仅用cpu是可以运行的
2.
是有遇到什么报错信息吗？这个包主要是langchain的unstructured包的文档页面要求安装的包，似乎并不是在所有文件格式读取过程中都需要用到。

奔腾年代-Jiaozn ***@***.***>于2023年4月3日 周一14:48写道：

**Comment by cristianohello** [comment]
@imClumsyPanda 
cpu跑有多慢，和gpu相比
