### ISSUE TITLE
Error loading punkt: <urlopen error [Errno 111] Connection

### ISSUE THREAD

**Issue by Shengrun2020** [imClumsyPanda/langchain-ChatGLM#70]
运行knowledge_based_chatglm.py，出现nltk报错，具体情况如下：
[nltk_data] Error loading punkt: <urlopen error [Errno 111] Connection
[nltk_data]     refused>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 111] Connection refused>
请问这是因为网络原因导致的吗，我试了三台机器，直接调用nltk.download()，下载nltk_data都会报错。

**Comment by imClumsyPanda** [comment]
按照 README 常见问题说明下载保存至本地路径后应该没问题，主要涉及到 nltk_data 不止一个包，请确认不同包都存储到相应位置后可以正常运行。

**Comment by Shengrun2020** [comment]
@imClumsyPanda 感谢帮助，已经成功解决了。
