### ISSUE TITLE
[BUG] webui.py运行报错，Error: CUDA out of memory. Tried to allocate more than 1EB memory

### ISSUE THREAD

**Issue by devillaws** [imClumsyPanda/langchain-ChatGLM#703]
问题描述:
webui.py
![fa88d4b9b7cabbb5a08953d7559bfbb](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/957a3dc5-001d-420d-a52f-4e9be9f038f8)
cli_demo.py
![671b2603fdd12e4f5256c4a0268a036](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/b5f57f02-30be-491a-a11f-15684a0a23ed)

复现问题的步骤
1. 执行 python cli_demo.py 或者 webui.py。
2. 问题出现：cli_demo的是RuntimeError: Storage size calculation overflowed with sizes=[4703721924520770560]，而webui.py的是Error: Storage size calculation overflowed with sizes=[4703721924520770560]。前缀不一样罢了。
3. 错误出现后，gradio的web可以正常使用，但是提示模型加载不成功。
4. 所有模型跟embedding经默认脚本下载到缓存目录中，即model_config.py没有修改过。

环境信息
- langchain-ChatGLM 版本/commit 号：fc57d76
- 是否使用 Docker 部署否
- 使用的模型：ChatGLM-6B-int4
- 使用的 Embedding 模型：GanymedeNil/text2vec-large-chinese
- 操作系统及版本：linux
- Python 版本：3.10
- 其他相关环境信息 ：
非root账号
CPU
![7d930fe3d3cc73a29c6d70c7879232c](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/a208167a-532d-4b66-b6e8-a51c85cec760)
![8fde866b5ec627b6e553b5b7a8a840d](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/612cd05a-c63d-44d7-9fce-0e790134a59b)
显卡
![3f457cbae68f02febdbcf22b9ff142d](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/74b8bc10-b229-44f7-8571-4fc9d40f2bf0)
硬盘
![b47024de456a3bf6d370101e69fffc7](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/8c7932c2-b1ed-41ef-9e7d-f4a89146c3d1)

**Comment by devillaws** [comment]
补一个webui.py启动后的nvidia-smi
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/ef4a61a9-6df1-4eb0-9c2d-342cd3b71edb)

**Comment by devillaws** [comment]
再补一个使用不量化的glm-6b，提示CUDA out of memory. Tried to allocate more than 1EB memory.
![52f53ded420c1b3849328c455921497](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/ec274a51-9e1e-4b49-8496-8e5bbbc43b0d)

**Comment by devillaws** [comment]
跑api.py，也是这个1EB memory错误
<img width="828" alt="a7d5b569b3570e29bc281381d5b7e50" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/4aaf8b29-5388-4a02-8f5b-d866e6b1c0bb">

**Comment by devillaws** [comment]
这两个修改为True，问题得以解决，可以正常启动使用了
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/aa7179b0-a361-4e15-8529-8e9a2fcf9b06)
附上正常启动的日志
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/2641348b-720b-4e46-8ece-973cb3099f70)

**Comment by tomFoxxxx** [comment]
没太看懂 3090正常跑GLM-6B是不需要量化的 为什么最后解决方案是量化加载8bit模型
