### ISSUE TITLE
[FEATURE] ChatGLM2支持

### ISSUE THREAD

**Issue by ljdavns** [imClumsyPanda/langchain-ChatGLM#704]
清华刚刚放出[ChatGLM2-6B](https://github.com/THUDM/ChatGLM2-6B)，6B模型在c-eval上达到了接近chatgpt的效果，满血模型超过了gpt4
![1a675ebaa2dd0cbe85f1e7e58eeaa4e](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/87931249/f39c9410-cbb6-4c04-bb97-ea69edd86239)

**Comment by xjwspeak** [comment]
+1

**Comment by SkySlity** [comment]
模型无法切换

**Comment by ljdavns** [comment]
好像最新更新的代码已经可以使用chatglm2了

**Comment by zhubao315** [comment]
vi /chatGLM/configs/model_config.py

    "chatglm-6b": {
        "name": "chatglm-6b",
        "pretrained_model_name": "THUDM/chatglm-6b",
        "local_model_path": "/data/models/chatglm2-6b/",
        "provides": "ChatGLM"
    },
