### ISSUE TITLE
救命，请问如何可以在这个工程下调用chatgpt-3.5的api呢？

### ISSUE THREAD

**Issue by ainndejj11** [imClumsyPanda/langchain-ChatGLM#710]
想对接 cahtgpt3.5，请问是否可以调用呢，如何调用？

**Comment by HS-LaoYao** [comment]
自己搜提交记录  ，复制到本地就行

**Comment by glide-the** [comment]
参见这个pr
https://github.com/imClumsyPanda/langchain-ChatGLM/pull/664/files#diff-2e3627c5c407891da5de007e1b31c683188b7a2ae47dc24c33a02e77cdb3a65aR140

**Comment by ainndejj11** [comment]
> 想对接 cahtgpt3.5，请问是否可以调用呢，如何调用？
