### ISSUE TITLE
4090单卡启动 cli_demo直接挂节点的问题

### ISSUE THREAD

**Issue by grantchenhuarong** [imClumsyPanda/langchain-ChatGLM#711]
各位大佬，刚刚开始接触本项目，按照ReadMe文档操作，启动cli_demo操作。输入文档路径，刚刚问第一个问题，节点就over了 ...有兄弟姐妹们撞见类似的情况么？

执行脚本：CUDA_VISIBLE_DEVICES=1 python cli_demo.py

求指点。。
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/44857880/f796c7ec-0a23-44b9-b4e2-b832d19b4888)

**Comment by hzg0601** [comment]
这是你远程主机的问题吧，远程主机设置的等待时长太短了

**Comment by grantchenhuarong** [comment]
主要是时间太巧合了，4卡机器跑都没跑动cli_demo，跑webui反而成功了。

**Comment by grantchenhuarong** [comment]
> 这是你远程主机的问题吧，远程主机设置的等待时长太短了

本地机器来的。
