### ISSUE TITLE
[BUG] 模型切换，由chatglm-6b切换到chatglm2-6b，点击“重新加载模型”，遇见bug

### ISSUE THREAD

**Issue by taotao033** [imClumsyPanda/langchain-ChatGLM#712]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
模型切换，由chatglm-6b切换到chatglm2-6b，点击“重新加载模型”，遇见bug：
ERROR 2023-06-26 10:51:57,151-1d: 'THUDM/chatglm-6b'

初步分析：
导致bug的原因
在models/shared.py 第11行 loaderLLM() 方法中  
pre_model_name = loaderCheckPoint.model_name
llm_model_info = llm_model_dict[pre_model_name]
此处llm_model_dict 找不到 THUDM/chatglm-6b
请检查该部分重新加载模型的逻辑，是否需要优化？

**Comment by glide-the** [comment]
config的模型地址需要是dict存在的
