### ISSUE TITLE
[不懂就问] ptuning数据集格式

### ISSUE THREAD

**Issue by sdhou** [imClumsyPanda/langchain-ChatGLM#72]
大家好请教 微调数据集的格式有什么玄机吗？我看 ChatGLM-6B/ptuning/readme.md的demo数据集ADGEN里content为啥都写成 类型#裙*风格#简约  这种格式的？这里面有啥玄机的？ 特此请教

**Comment by imClumsyPanda** [comment]
本项目不涉及微调过程，详见`README.md`第一部分
