### ISSUE TITLE
[BUG] MacPro上M1-16G内存上传文件夹卡主

### ISSUE THREAD

**Issue by Veken** [imClumsyPanda/langchain-ChatGLM#725]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/12594017/27202dd7-437e-4eaf-ab9e-cac351941edd)
上传只有一个1M的word文件的文件夹，都卡主不动了，也没有任何错误日志输出，查看活动监视器，内存和CPU占用都还好，不知道啥原因

**Comment by niudun123-liao** [comment]
我也遇到这个问题了，之前都还正常，昨天拉取了最新的代码就这样了，不知道是什么原因

**Comment by niudun123-liao** [comment]
我又尝试了一下，确认了以下情况：
拖动文件夹传入会卡住不动，但如果点击进入从文档系统中选择文件夹是可以传入的。
怀疑是gradio的bug

**Comment by Veken** [comment]
>

**Comment by Veken** [comment]
> 我又尝试了一下，确认了以下情况： 拖动文件夹传入会卡住不动，但如果点击进入从文档系统中选择文件夹是可以传入的。 怀疑是gradio的bug

好像确实是这样，不能直接拖动
