### ISSUE TITLE
Embedding model请教

### ISSUE THREAD

**Issue by XiaoYee** [imClumsyPanda/langchain-ChatGLM#74]
您好，我看到项目里的embedding模型用的是：GanymedeNil/text2vec-large-chinese，请问这个项目里的embedding模型可以直接用ChatGLM嘛？

**Comment by Garen-in-bush** [comment]
> chatglm-6b 暂未提供 embedding 接口

现已加载了chatglm-6b的model以及tokennizer
我尝试用下面的代码对输入文本进行embedding
`temp = torch.tensor(tokenizer.encode(input)).to('cuda:0')
 print(temp)
 print(model.transformer.word_embeddings(temp))`
得到下面的输出
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/50519434/8d31a88b-1f4d-42e7-8120-36bbc77533a7)
后续我试试能不能使用这个作为langchain的embedding
