### ISSUE TITLE
运行报错：AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by WackyZet** [imClumsyPanda/langchain-ChatGLM#8]
报错：
lib/python3.10/site-packages/tensorboard/compat/proto/histogram_pb2.py", line 21, in <module>
    _HISTOGRAMPROTO = DESCRIPTOR.message_types_by_name['HistogramProto']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

**Comment by imClumsyPanda** [comment]
目前已做过测试的环境是python 3.8，建议测试一下其他新建3.8环境

WackyZet ***@***.***>于2023年4月3日 周一16:37写道：

**Comment by zqt996** [comment]
3.8



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月25日 00:16 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [imClumsyPanda/langchain-ChatGLM] 运行报错：AttributeError: 'NoneType' object has no attribute 'message_types_by_name' (Issue #8) |

同样的错误，我的环境是3.10

**Comment by junxin367** [comment]
pip install --upgrade protobuf==3.19.6
