### ISSUE TITLE
[BUG]webui切换模型失败ValueError: The device_map provided does not give any device for the following parameters: 

### ISSUE THREAD

**Issue by YeHaijia** [imClumsyPanda/langchain-ChatGLM#829]
机器：2x3090
初始化chatglm成功，换chatglm2失败
初始化chatglm2成功，切换chatglm失败

以下为glm2切到glm
Loading THUDM/chatglm-6b...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:06<00:00,  1.15it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "webui.py", line 127, in reinit_model
    llm_model_ins = shared.loaderLLM(llm_model, no_remote_model, use_ptuning_v2)
  File "/workspace/nas-data/langchain-ChatGLM/models/shared.py", line 41, in loaderLLM
    loaderCheckPoint.reload_model()
  File "/workspace/nas-data/langchain-ChatGLM/models/loader/loader.py", line 430, in reload_model
    self.model, self.tokenizer = self._load_model(self.model_name)
  File "/workspace/nas-data/langchain-ChatGLM/models/loader/loader.py", line 145, in _load_model
    model = dispatch_model(model, device_map=self.device_map)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/big_modeling.py", line 330, in dispatch_model
    check_device_map(model, device_map)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/utils/modeling.py", line 902, in check_device_map
    raise ValueError(
ValueError: The device_map provided does not give any device for the following parameters: transformer.word_embeddings.weight, transformer.layers.0.input_layernorm.weight, transformer.layers.0.input_layernorm.bias, transformer.layers.0.attention.rotary_emb.inv_freq, transformer.layers.0.attention.query_key_value.weight, transformer.layers.0.attention.query_key_value.bias, transformer.layers.0.attention.dense.weight, transformer.layers.0.attention.dense.bias, transformer.layers.0.post_attention_layernorm.weight, transformer.layers.0.post_attention_layernorm.bias, transformer.layers.0.mlp.dense_h_to_4h.weight, transformer.layers.0.mlp.dense_h_to_4h.bias, transformer.layers.0.mlp.dense_4h_to_h.weight, transformer.layers.0.mlp.dense_4h_to_h.bias, transformer.layers.1.input_layernorm.weight, transformer.layers.1.input_layernorm.bias, transformer.layers.1.attention.rotary_emb.inv_freq, transformer.layers.1.attention.query_key_value.weight, transformer.layers.1.attention.query_key_value.bias, transformer.layers.1.attention.dense.weight, transformer.layers.1.attention.dense.bias, transformer.layers.1.post_attention_layernorm.weight, transformer.layers.1.post_attention_layernorm.bias, transformer.layers.1.mlp.dense_h_to_4h.weight, transformer.layers.1.mlp.dense_h_to_4h.bias, transformer.layers.1.mlp.dense_4h_to_h.weight, transformer.layers.1.mlp.dense_4h_to_h.bias, transformer.layers.2.input_layernorm.weight, transformer.layers.2.input_layernorm.bias, transformer.layers.2.attention.rotary_emb.inv_freq, transformer.layers.2.attention.query_key_value.weight, transformer.layers.2.attention.query_key_value.bias, transformer.layers.2.attention.dense.weight, transformer.layers.2.attention.dense.bias, transformer.layers.2.post_attention_layernorm.weight, transformer.layers.2.post_attention_layernorm.bias, transformer.layers.2.mlp.dense_h_to_4h.weight, transformer.layers.2.mlp.dense_h_to_4h.bias, transformer.layers.2.mlp.dense_4h_to_h.weight, transformer.layers.2.mlp.dense_4h_to_h.bias, transformer.layers.3.input_layernorm.weight, transformer.layers.3.input_layernorm.bias, transformer.layers.3.attention.rotary_emb.inv_freq, transformer.layers.3.attention.query_key_value.weight, transformer.layers.3.attention.query_key_value.bias, transformer.layers.3.attention.dense.weight, transformer.layers.3.attention.dense.bias, transformer.layers.3.post_attention_layernorm.weight, transformer.layers.3.post_attention_layernorm.bias, transformer.layers.3.mlp.dense_h_to_4h.weight, transformer.layers.3.mlp.dense_h_to_4h.bias, transformer.layers.3.mlp.dense_4h_to_h.weight, transformer.layers.3.mlp.dense_4h_to_h.bias, transformer.layers.4.input_layernorm.weight, transformer.layers.4.input_layernorm.bias, transformer.layers.4.attention.rotary_emb.inv_freq, transformer.layers.4.attention.query_key_value.weight, transformer.layers.4.attention.query_key_value.bias, transformer.layers.4.attention.dense.weight, transformer.layers.4.attention.dense.bias, transformer.layers.4.post_attention_layernorm.weight, transformer.layers.4.post_attention_layernorm.bias, transformer.layers.4.mlp.dense_h_to_4h.weight, transformer.layers.4.mlp.dense_h_to_4h.bias, transformer.layers.4.mlp.dense_4h_to_h.weight, transformer.layers.4.mlp.dense_4h_to_h.bias, transformer.layers.5.input_layernorm.weight, transformer.layers.5.input_layernorm.bias, transformer.layers.5.attention.rotary_emb.inv_freq, transformer.layers.5.attention.query_key_value.weight, transformer.layers.5.attention.query_key_value.bias, transformer.layers.5.attention.dense.weight, transformer.layers.5.attention.dense.bias, transformer.layers.5.post_attention_layernorm.weight, transformer.layers.5.post_attention_layernorm.bias, transformer.layers.5.mlp.dense_h_to_4h.weight, transformer.layers.5.mlp.dense_h_to_4h.bias, transformer.layers.5.mlp.dense_4h_to_h.weight, transformer.layers.5.mlp.dense_4h_to_h.bias, transformer.layers.6.input_layernorm.weight, transformer.layers.6.input_layernorm.bias, transformer.layers.6.attention.rotary_emb.inv_freq, transformer.layers.6.attention.query_key_value.weight, transformer.layers.6.attention.query_key_value.bias, transformer.layers.6.attention.dense.weight, transformer.layers.6.attention.dense.bias, transformer.layers.6.post_attention_layernorm.weight, transformer.layers.6.post_attention_layernorm.bias, transformer.layers.6.mlp.dense_h_to_4h.weight, transformer.layers.6.mlp.dense_h_to_4h.bias, transformer.layers.6.mlp.dense_4h_to_h.weight, transformer.layers.6.mlp.dense_4h_to_h.bias, transformer.layers.7.input_layernorm.weight, transformer.layers.7.input_layernorm.bias, transformer.layers.7.attention.rotary_emb.inv_freq, transformer.layers.7.attention.query_key_value.weight, transformer.layers.7.attention.query_key_value.bias, transformer.layers.7.attention.dense.weight, transformer.layers.7.attention.dense.bias, transformer.layers.7.post_attention_layernorm.weight, transformer.layers.7.post_attention_layernorm.bias, transformer.layers.7.mlp.dense_h_to_4h.weight, transformer.layers.7.mlp.dense_h_to_4h.bias, transformer.layers.7.mlp.dense_4h_to_h.weight, transformer.layers.7.mlp.dense_4h_to_h.bias, transformer.layers.8.input_layernorm.weight, transformer.layers.8.input_layernorm.bias, transformer.layers.8.attention.rotary_emb.inv_freq, transformer.layers.8.attention.query_key_value.weight, transformer.layers.8.attention.query_key_value.bias, transformer.layers.8.attention.dense.weight, transformer.layers.8.attention.dense.bias, transformer.layers.8.post_attention_layernorm.weight, transformer.layers.8.post_attention_layernorm.bias, transformer.layers.8.mlp.dense_h_to_4h.weight, transformer.layers.8.mlp.dense_h_to_4h.bias, transformer.layers.8.mlp.dense_4h_to_h.weight, transformer.layers.8.mlp.dense_4h_to_h.bias, transformer.layers.9.input_layernorm.weight, transformer.layers.9.input_layernorm.bias, transformer.layers.9.attention.rotary_emb.inv_freq, transformer.layers.9.attention.query_key_value.weight, transformer.layers.9.attention.query_key_value.bias, transformer.layers.9.attention.dense.weight, transformer.layers.9.attention.dense.bias, transformer.layers.9.post_attention_layernorm.weight, transformer.layers.9.post_attention_layernorm.bias, transformer.layers.9.mlp.dense_h_to_4h.weight, transformer.layers.9.mlp.dense_h_to_4h.bias, transformer.layers.9.mlp.dense_4h_to_h.weight, transformer.layers.9.mlp.dense_4h_to_h.bias, transformer.layers.10.input_layernorm.weight, transformer.layers.10.input_layernorm.bias, transformer.layers.10.attention.rotary_emb.inv_freq, transformer.layers.10.attention.query_key_value.weight, transformer.layers.10.attention.query_key_value.bias, transformer.layers.10.attention.dense.weight, transformer.layers.10.attention.dense.bias, transformer.layers.10.post_attention_layernorm.weight, transformer.layers.10.post_attention_layernorm.bias, transformer.layers.10.mlp.dense_h_to_4h.weight, transformer.layers.10.mlp.dense_h_to_4h.bias, transformer.layers.10.mlp.dense_4h_to_h.weight, transformer.layers.10.mlp.dense_4h_to_h.bias, transformer.layers.11.input_layernorm.weight, transformer.layers.11.input_layernorm.bias, transformer.layers.11.attention.rotary_emb.inv_freq, transformer.layers.11.attention.query_key_value.weight, transformer.layers.11.attention.query_key_value.bias, transformer.layers.11.attention.dense.weight, transformer.layers.11.attention.dense.bias, transformer.layers.11.post_attention_layernorm.weight, transformer.layers.11.post_attention_layernorm.bias, transformer.layers.11.mlp.dense_h_to_4h.weight, transformer.layers.11.mlp.dense_h_to_4h.bias, transformer.layers.11.mlp.dense_4h_to_h.weight, transformer.layers.11.mlp.dense_4h_to_h.bias, transformer.layers.12.input_layernorm.weight, transformer.layers.12.input_layernorm.bias, transformer.layers.12.attention.rotary_emb.inv_freq, transformer.layers.12.attention.query_key_value.weight, transformer.layers.12.attention.query_key_value.bias, transformer.layers.12.attention.dense.weight, transformer.layers.12.attention.dense.bias, transformer.layers.12.post_attention_layernorm.weight, transformer.layers.12.post_attention_layernorm.bias, transformer.layers.12.mlp.dense_h_to_4h.weight, transformer.layers.12.mlp.dense_h_to_4h.bias, transformer.layers.12.mlp.dense_4h_to_h.weight, transformer.layers.12.mlp.dense_4h_to_h.bias, transformer.layers.13.input_layernorm.weight, transformer.layers.13.input_layernorm.bias, transformer.layers.13.attention.rotary_emb.inv_freq, transformer.layers.13.attention.query_key_value.weight, transformer.layers.13.attention.query_key_value.bias, transformer.layers.13.attention.dense.weight, transformer.layers.13.attention.dense.bias, transformer.layers.13.post_attention_layernorm.weight, transformer.layers.13.post_attention_layernorm.bias, transformer.layers.13.mlp.dense_h_to_4h.weight, transformer.layers.13.mlp.dense_h_to_4h.bias, transformer.layers.13.mlp.dense_4h_to_h.weight, transformer.layers.13.mlp.dense_4h_to_h.bias, transformer.layers.14.input_layernorm.weight, transformer.layers.14.input_layernorm.bias, transformer.layers.14.attention.rotary_emb.inv_freq, transformer.layers.14.attention.query_key_value.weight, transformer.layers.14.attention.query_key_value.bias, transformer.layers.14.attention.dense.weight, transformer.layers.14.attention.dense.bias, transformer.layers.14.post_attention_layernorm.weight, transformer.layers.14.post_attention_layernorm.bias, transformer.layers.14.mlp.dense_h_to_4h.weight, transformer.layers.14.mlp.dense_h_to_4h.bias, transformer.layers.14.mlp.dense_4h_to_h.weight, transformer.layers.14.mlp.dense_4h_to_h.bias, transformer.layers.15.input_layernorm.weight, transformer.layers.15.input_layernorm.bias, transformer.layers.15.attention.rotary_emb.inv_freq, transformer.layers.15.attention.query_key_value.weight, transformer.layers.15.attention.query_key_value.bias, transformer.layers.15.attention.dense.weight, transformer.layers.15.attention.dense.bias, transformer.layers.15.post_attention_layernorm.weight, transformer.layers.15.post_attention_layernorm.bias, transformer.layers.15.mlp.dense_h_to_4h.weight, transformer.layers.15.mlp.dense_h_to_4h.bias, transformer.layers.15.mlp.dense_4h_to_h.weight, transformer.layers.15.mlp.dense_4h_to_h.bias, transformer.layers.16.input_layernorm.weight, transformer.layers.16.input_layernorm.bias, transformer.layers.16.attention.rotary_emb.inv_freq, transformer.layers.16.attention.query_key_value.weight, transformer.layers.16.attention.query_key_value.bias, transformer.layers.16.attention.dense.weight, transformer.layers.16.attention.dense.bias, transformer.layers.16.post_attention_layernorm.weight, transformer.layers.16.post_attention_layernorm.bias, transformer.layers.16.mlp.dense_h_to_4h.weight, transformer.layers.16.mlp.dense_h_to_4h.bias, transformer.layers.16.mlp.dense_4h_to_h.weight, transformer.layers.16.mlp.dense_4h_to_h.bias, transformer.layers.17.input_layernorm.weight, transformer.layers.17.input_layernorm.bias, transformer.layers.17.attention.rotary_emb.inv_freq, transformer.layers.17.attention.query_key_value.weight, transformer.layers.17.attention.query_key_value.bias, transformer.layers.17.attention.dense.weight, transformer.layers.17.attention.dense.bias, transformer.layers.17.post_attention_layernorm.weight, transformer.layers.17.post_attention_layernorm.bias, transformer.layers.17.mlp.dense_h_to_4h.weight, transformer.layers.17.mlp.dense_h_to_4h.bias, transformer.layers.17.mlp.dense_4h_to_h.weight, transformer.layers.17.mlp.dense_4h_to_h.bias, transformer.layers.18.input_layernorm.weight, transformer.layers.18.input_layernorm.bias, transformer.layers.18.attention.rotary_emb.inv_freq, transformer.layers.18.attention.query_key_value.weight, transformer.layers.18.attention.query_key_value.bias, transformer.layers.18.attention.dense.weight, transformer.layers.18.attention.dense.bias, transformer.layers.18.post_attention_layernorm.weight, transformer.layers.18.post_attention_layernorm.bias, transformer.layers.18.mlp.dense_h_to_4h.weight, transformer.layers.18.mlp.dense_h_to_4h.bias, transformer.layers.18.mlp.dense_4h_to_h.weight, transformer.layers.18.mlp.dense_4h_to_h.bias, transformer.layers.19.input_layernorm.weight, transformer.layers.19.input_layernorm.bias, transformer.layers.19.attention.rotary_emb.inv_freq, transformer.layers.19.attention.query_key_value.weight, transformer.layers.19.attention.query_key_value.bias, transformer.layers.19.attention.dense.weight, transformer.layers.19.attention.dense.bias, transformer.layers.19.post_attention_layernorm.weight, transformer.layers.19.post_attention_layernorm.bias, transformer.layers.19.mlp.dense_h_to_4h.weight, transformer.layers.19.mlp.dense_h_to_4h.bias, transformer.layers.19.mlp.dense_4h_to_h.weight, transformer.layers.19.mlp.dense_4h_to_h.bias, transformer.layers.20.input_layernorm.weight, transformer.layers.20.input_layernorm.bias, transformer.layers.20.attention.rotary_emb.inv_freq, transformer.layers.20.attention.query_key_value.weight, transformer.layers.20.attention.query_key_value.bias, transformer.layers.20.attention.dense.weight, transformer.layers.20.attention.dense.bias, transformer.layers.20.post_attention_layernorm.weight, transformer.layers.20.post_attention_layernorm.bias, transformer.layers.20.mlp.dense_h_to_4h.weight, transformer.layers.20.mlp.dense_h_to_4h.bias, transformer.layers.20.mlp.dense_4h_to_h.weight, transformer.layers.20.mlp.dense_4h_to_h.bias, transformer.layers.21.input_layernorm.weight, transformer.layers.21.input_layernorm.bias, transformer.layers.21.attention.rotary_emb.inv_freq, transformer.layers.21.attention.query_key_value.weight, transformer.layers.21.attention.query_key_value.bias, transformer.layers.21.attention.dense.weight, transformer.layers.21.attention.dense.bias, transformer.layers.21.post_attention_layernorm.weight, transformer.layers.21.post_attention_layernorm.bias, transformer.layers.21.mlp.dense_h_to_4h.weight, transformer.layers.21.mlp.dense_h_to_4h.bias, transformer.layers.21.mlp.dense_4h_to_h.weight, transformer.layers.21.mlp.dense_4h_to_h.bias, transformer.layers.22.input_layernorm.weight, transformer.layers.22.input_layernorm.bias, transformer.layers.22.attention.rotary_emb.inv_freq, transformer.layers.22.attention.query_key_value.weight, transformer.layers.22.attention.query_key_value.bias, transformer.layers.22.attention.dense.weight, transformer.layers.22.attention.dense.bias, transformer.layers.22.post_attention_layernorm.weight, transformer.layers.22.post_attention_layernorm.bias, transformer.layers.22.mlp.dense_h_to_4h.weight, transformer.layers.22.mlp.dense_h_to_4h.bias, transformer.layers.22.mlp.dense_4h_to_h.weight, transformer.layers.22.mlp.dense_4h_to_h.bias, transformer.layers.23.input_layernorm.weight, transformer.layers.23.input_layernorm.bias, transformer.layers.23.attention.rotary_emb.inv_freq, transformer.layers.23.attention.query_key_value.weight, transformer.layers.23.attention.query_key_value.bias, transformer.layers.23.attention.dense.weight, transformer.layers.23.attention.dense.bias, transformer.layers.23.post_attention_layernorm.weight, transformer.layers.23.post_attention_layernorm.bias, transformer.layers.23.mlp.dense_h_to_4h.weight, transformer.layers.23.mlp.dense_h_to_4h.bias, transformer.layers.23.mlp.dense_4h_to_h.weight, transformer.layers.23.mlp.dense_4h_to_h.bias, transformer.layers.24.input_layernorm.weight, transformer.layers.24.input_layernorm.bias, transformer.layers.24.attention.rotary_emb.inv_freq, transformer.layers.24.attention.query_key_value.weight, transformer.layers.24.attention.query_key_value.bias, transformer.layers.24.attention.dense.weight, transformer.layers.24.attention.dense.bias, transformer.layers.24.post_attention_layernorm.weight, transformer.layers.24.post_attention_layernorm.bias, transformer.layers.24.mlp.dense_h_to_4h.weight, transformer.layers.24.mlp.dense_h_to_4h.bias, transformer.layers.24.mlp.dense_4h_to_h.weight, transformer.layers.24.mlp.dense_4h_to_h.bias, transformer.layers.25.input_layernorm.weight, transformer.layers.25.input_layernorm.bias, transformer.layers.25.attention.rotary_emb.inv_freq, transformer.layers.25.attention.query_key_value.weight, transformer.layers.25.attention.query_key_value.bias, transformer.layers.25.attention.dense.weight, transformer.layers.25.attention.dense.bias, transformer.layers.25.post_attention_layernorm.weight, transformer.layers.25.post_attention_layernorm.bias, transformer.layers.25.mlp.dense_h_to_4h.weight, transformer.layers.25.mlp.dense_h_to_4h.bias, transformer.layers.25.mlp.dense_4h_to_h.weight, transformer.layers.25.mlp.dense_4h_to_h.bias, transformer.layers.26.input_layernorm.weight, transformer.layers.26.input_layernorm.bias, transformer.layers.26.attention.rotary_emb.inv_freq, transformer.layers.26.attention.query_key_value.weight, transformer.layers.26.attention.query_key_value.bias, transformer.layers.26.attention.dense.weight, transformer.layers.26.attention.dense.bias, transformer.layers.26.post_attention_layernorm.weight, transformer.layers.26.post_attention_layernorm.bias, transformer.layers.26.mlp.dense_h_to_4h.weight, transformer.layers.26.mlp.dense_h_to_4h.bias, transformer.layers.26.mlp.dense_4h_to_h.weight, transformer.layers.26.mlp.dense_4h_to_h.bias, transformer.layers.27.input_layernorm.weight, transformer.layers.27.input_layernorm.bias, transformer.layers.27.attention.rotary_emb.inv_freq, transformer.layers.27.attention.query_key_value.weight, transformer.layers.27.attention.query_key_value.bias, transformer.layers.27.attention.dense.weight, transformer.layers.27.attention.dense.bias, transformer.layers.27.post_attention_layernorm.weight, transformer.layers.27.post_attention_layernorm.bias, transformer.layers.27.mlp.dense_h_to_4h.weight, transformer.layers.27.mlp.dense_h_to_4h.bias, transformer.layers.27.mlp.dense_4h_to_h.weight, transformer.layers.27.mlp.dense_4h_to_h.bias, transformer.final_layernorm.weight, transformer.final_layernorm.bias, lm_head.weight

**Comment by crowningwang** [comment]
同样的问题

**Comment by crowningwang** [comment]
解决了，device map里面有个if去掉

**Comment by GanJiang98** [comment]
> 



> 解决了，device map里面有个if去掉

可以再具体说一下嘛 感恩的心

**Comment by sralvins** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/24619551/0df2db21-5691-40cc-aecf-e4540fabb979)
models/loader/loader.py文件里的_load_model方法里先后调用chatglm_auto_configure_device_map和dispatch_model方法。此时还未加载lora权重，模型还不是PeftModel，但chatglm_auto_configure_device_map已经按照PeftModel的名称分配设备了，所以dispatch_model的时候会报错，要么向上面说的那样改，把chatglm_auto_configure_device_map里的`if lora`那块注释，后面加载lora权重也会自动分配设备，要么把dispatch_model放到加载lora权重后

**Comment by YeHaijia** [comment]
> ![image](https://user-images.githubusercontent.com/24619551/253462998-0df2db21-5691-40cc-aecf-e4540fabb979.png) models/loader/loader.py文件里的_load_model方法里先后调用chatglm_auto_configure_device_map和dispatch_model方法。此时还未加载lora权重，模型还不是PeftModel，但chatglm_auto_configure_device_map已经按照PeftModel的名称分配设备了，所以dispatch_model的时候会报错，要么像上面说的那样改，把chatglm_auto_configure_device_map里的`if lora`那块注释，后面加载lora权重也会自动分配设备，要么把dispatch_model放到加载lora权重后

之注释掉432行的if 好像还不行呀

**Comment by sralvins** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/24619551/e1cad075-8b8d-482a-afca-b77d77a0ee4d)

你看不懂人类语言吗

**Comment by sralvins** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/24619551/20a9e6f5-c06d-47be-9d70-c9c2ad7b26ab)

**Comment by crowningwang** [comment]
> > 
> 
> > 解决了，设备地图里面有个if去掉
> 
> 可以再具体说一下感恩的心

loader里面if self.device_map is None:这个注释掉，这样模型切换就没问题了，不然一直是初始模型的device map分配

**Comment by crowningwang** [comment]
> > ![image](https://user-images.githubusercontent.com/24619551/253462998-0df2db21-5691-40cc-aecf-e4540fabb979.png) models/loader/loader.py文件里的_load_model方法里先后调用chatglm_auto_configure_device_map和dispatch_model方法。此时还未加载lora权重，模型还不是PeftModel，但chatglm_auto_configure_device_map已经按照PeftModel的名称分配设备了，所以dispatch_model的时候会报错，要么像上面说的那样改，把chatglm_auto_configure_device_map里的`if lora`那块注释，后面加载lora权重也会自动分配设备，要么把dispatch_model放到加载lora权重后
> 
> 之注释掉432行的if 好像还不行呀

注释Loader里面的

**Comment by YeHaijia** [comment]
可以了，注释掉loader文件的if self.device_map is None:

**Comment by gitgoready** [comment]
注释掉之后
                    # if self.device_map is None:
                    #     if 'chatglm' in model_name.lower():
                    #         self.device_map = self.chatglm_auto_configure_device_map(num_gpus)
                    #     elif 'moss' in model_name.lower():
                    #         self.device_map = self.moss_auto_configure_device_map(num_gpus, model_name)
                    #     else:
                    #         self.device_map = self.chatglm_auto_configure_device_map(num_gpus)
没解决，device_map变为None，后面报错：

(textgen) zjs@zjs-ProLiant-DL388-Gen10:~/zjs/zy/chatglm/KG-ChatGLM/langchain-ChatGLM-0.1.16$ python webui.py
INFO  2023-08-01 19:22:59,714-1d:
loading model config
llm device: cuda
embedding device: cuda
dir: /home/zjs/zjs/zy/chatglm/KG-ChatGLM/langchain-ChatGLM-0.1.16
flagging username: 1874c2f64da1425295997f0e1a674d5a

Loading /home/zjs/zjs/zy/chatglm/KG-ChatGLM/model-glm2...
Loading checkpoint shards: 100%|████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.51s/it]
None
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/zjs/zjs/zy/chatglm/KG-ChatGLM/langchain-ChatGLM-0.1.16/webui.py:322 in <module>            │
│                                                                                                  │
│   319 """                                                                                        │
│   320                                                                                            │
│   321 # 初始化消息                                                                               │
│ ❱ 322 model_status = init_model()                                                                │
│   323                                                                                            │
│   324 default_theme_args = dict(                                                                 │
│   325 │   font=["Source Sans Pro", 'ui-sans-serif', 'system-ui', 'sans-serif'],                  │
│                                                                                                  │
│ /home/zjs/zjs/zy/chatglm/KG-ChatGLM/langchain-ChatGLM-0.1.16/webui.py:103 in init_model          │
│                                                                                                  │
│   100 │                                                                                          │
│   101 │   args_dict = vars(args)                                                                 │
│   102 │   shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                                  │
│ ❱ 103 │   llm_model_ins = shared.loaderLLM()                                                     │
│   104 │   llm_model_ins.set_history_len(LLM_HISTORY_LEN)                                         │
│   105 │   try:                                                                                   │
│   106 │   │   local_doc_qa.init_cfg(llm_model=llm_model_ins)                                     │
│                                                                                                  │
│ /home/zjs/zjs/zy/chatglm/KG-ChatGLM/langchain-ChatGLM-0.1.16/models/shared.py:40 in loaderLLM    │
│                                                                                                  │
│   37 │   if 'FastChatOpenAILLM' in llm_model_info["provides"]:                                   │
│   38 │   │   loaderCheckPoint.unload_model()                                                     │
│   39 │   else:                                                                                   │
│ ❱ 40 │   │   loaderCheckPoint.reload_model()                                                     │
│   41 │                                                                                           │
│   42 │   provides_class = getattr(sys.modules['models'], llm_model_info['provides'])             │
│   43 │   modelInsLLM = provides_class(checkPoint=loaderCheckPoint)                               │
│                                                                                                  │
│ /home/zjs/zjs/zy/chatglm/KG-ChatGLM/langchain-ChatGLM-0.1.16/models/loader/loader.py:420 in      │
│ reload_model                                                                                     │
│                                                                                                  │
│   417 │   │   │   except Exception as e:                                                         │
│   418 │   │   │   │   print("加载PrefixEncoder config.json失败")                                 │
│   419 │   │                                                                                      │
│ ❱ 420 │   │   self.model, self.tokenizer = self._load_model(self.model_name)                     │
│   421 │   │                                                                                      │
│   422 │   │   if self.lora:                                                                      │
│   423 │   │   │   self._add_lora_to_model([self.lora])                                           │
│                                                                                                  │
│ /home/zjs/zjs/zy/chatglm/KG-ChatGLM/langchain-ChatGLM-0.1.16/models/loader/loader.py:146 in      │
│ _load_model                                                                                      │
│                                                                                                  │
│   143 │   │   │   │   │   #         self.device_map = self.chatglm_auto_configure_device_map(n   │
│   144 │   │   │   │   │   print(self.device_map)                                                 │
│   145 │   │   │   │   │                                                                          │
│ ❱ 146 │   │   │   │   │   model = dispatch_model(model, device_map=self.device_map)              │
│   147 │   │   │   else:                                                                          │
│   148 │   │   │   │   model = (                                                                  │
│   149 │   │   │   │   │   LoaderClass.from_pretrained(                                           │
│                                                                                                  │
│ /home/zjs/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/big_modeling.py:327 in  │
│ dispatch_model                                                                                   │
│                                                                                                  │
│   324 │   if not is_torch_version(">=", "1.9.0"):                                                │
│   325 │   │   raise NotImplementedError("Model dispatching requires torch >= 1.9.0")             │
│   326 │   # Error early if the device map is incomplete.                                         │
│ ❱ 327 │   check_device_map(model, device_map)                                                    │
│   328 │                                                                                          │
│   329 │   if main_device is None:                                                                │
│   330 │   │   if set(device_map.values()) == {"cpu"} or set(device_map.values()) == {"cpu", "d   │
│                                                                                                  │
│ /home/zjs/anaconda3/envs/textgen/lib/python3.10/site-packages/accelerate/utils/modeling.py:754   │
│ in check_device_map                                                                              │
│                                                                                                  │
│   751 │   │   device_map (`Dict[str, Union[int, str, torch.device]]`): The device map to check   │
│   752 │   """                                                                                    │
│   753 │   all_model_tensors = [name for name, _ in model.state_dict().items()]                   │
│ ❱ 754 │   for module_name in device_map.keys():                                                  │
│   755 │   │   all_model_tensors = [name for name in all_model_tensors if not name.startswith(m   │
│   756 │   if len(all_model_tensors) > 0:                                                         │
│   757 │   │   non_covered_params = ", ".join(all_model_tensors)                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'keys'
