### ISSUE TITLE
[BUG]  ERROR: Failed building wheel for pycocotools每次配环境都报这个错 试了很多方法都没解决

### ISSUE THREAD

**Issue by zhuozj22** [imClumsyPanda/langchain-ChatGLM#833]
![df27716d56af1e361b4cc5c7a90187a](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/126583941/538d85c9-ea1f-4ede-8890-c245c69c5b90)
![df27716d56af1e361b4cc5c7a90187a](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/126583941/538d85c9-ea1f-4ede-8890-c245c69c5b90)

**Comment by imClumsyPanda** [comment]
error: Microsoft Visual C+ 14.0 or greater is required. Get it with "Microsoft C+* Build Tools": https://visualstudio. microsoft. com/visual-epp-build-tools/
