### ISSUE TITLE
[BUG] 调用openai报错

### ISSUE THREAD

**Issue by JJshen666** [imClumsyPanda/langchain-ChatGLM#843]
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openapi.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
我已经将urllib3版本修改为1.25.11，并开启了代理，还是报错

**Comment by FizzerYu** [comment]
这个仓库的代理是自己的代理，你要改一下，修改为【https://api.openai.com/v1】就好（少一个p）
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/36132150/db53c9ed-6a30-45e0-b8cd-771bebccebd0)

**Comment by JJshen666** [comment]
感谢！
