### ISSUE TITLE
[BUG]加载ptuning-v2训练的模型报错：ChatGLMModel' object has no attribute 'prefix_encoder'

### ISSUE THREAD

**Issue by tendrillion** [imClumsyPanda/langchain-ChatGLM#847]
**问题描述 / Problem Description**
加载ptuning-v2训练的模型报错。提示：
'ChatGLMModel' object has no attribute 'prefix_encoder'

**复现问题的步骤 / Steps to Reproduce**
1. ptuning-v2训练的模型的config.json和pytorch_model.bin，放入ptuning-v2文件夹；
2. 运行python webui.py 或者api.py时，加载PrefixEncoder config.json成功，但是加载PrefixEncoder模型参数失败，提示：ChatGLMModel' object has no attribute 'prefix_encoder'

**Comment by MingjunHu** [comment]
微调的时候 quantization_bit 8
这个值写的多少？

**Comment by MingjunHu** [comment]
请教个问题：
微调的时候 quantization_bit
这个值写的多少？
你启动 webui.py 时 configs/model_config.py 里的 LOAD_IN_8BIT 是True吗？  我怎么总是 报“加载PrefixEncoder模型参数失败
”呢？

**Comment by tendrillion** [comment]
微调的时候 quantization_bit=8
启动 webui.py 时 configs/model_config.py 里的 LOAD_IN_8BIT 是True
执行到：self.model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
报错:'ChatGLMModel' object has no attribute 'prefix_encoder'

**Comment by tendrillion** [comment]
> 微调的时候 quantization_bit=8
> 启动 webui.py 时 configs/model_config.py 里的 LOAD_IN_8BIT 是True
> 执行到：self.model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
> 报错:'ChatGLMModel' object has no attribute 'prefix_encoder'

**Comment by tendrillion** [comment]
> 

微调的时候 quantization_bit=8
启动 webui.py 时 configs/model_config.py 里的 LOAD_IN_8BIT 是True
执行到：self.model.transformer.prefix_encoder.load_state_dict(new_prefix_state_dict)
报错:'ChatGLMModel' object has no attribute 'prefix_encoder'

**Comment by hzg0601** [comment]
dev分支 commit 3b6819f已修复此问题，当前关闭issue，如果仍有问题请重开
