### ISSUE TITLE
[BUG] models/fastchat_openai_llm.py中的143行代码messages=build_message_list(prompt)，遗漏history参数

### ISSUE THREAD

**Issue by chenyuqiang234** [imClumsyPanda/langchain-ChatGLM#851]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/53166988/9be23d75-ea87-4e95-a02b-e9b115d63f80)
此处遗漏掉history参数，运行时会报错，请及时修正。

**Comment by imClumsyPanda** [comment]
已在 dev 分支中修复，将尽快汇入 master 分支
