### ISSUE TITLE
TypeError: MyFAISS.similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'

### ISSUE THREAD

**Issue by MrDaoyuan** [imClumsyPanda/langchain-ChatGLM#860]
使用知识库时，报错TypeError: MyFAISS.similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'
<img width="638" alt="屏幕截图 2023-07-16 175959" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/97818600/370f568b-d4f5-40d0-b6ae-1b77b0e24d7c">
问了模型，但不知道怎么操作：
<img width="968" alt="屏幕截图 2023-07-16 175844" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/97818600/7febd715-5b00-4f7b-9ade-5fa6f64c6424">

**Comment by Canqiang** [comment]
我也遇到了同样的问题

**Comment by Canqiang** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/739#issuecomment-1617712252

有个回答是说降低langchain的版本到0.0.174

**Comment by MrDaoyuan** [comment]
> 

你尝试之后，解决这个问题了吗？我己经降到0.0.174了，但出现了新的bug，关于langchain.shema.document的

**Comment by MrDaoyuan** [comment]
> [#739 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/739#issuecomment-1617712252)
> 
> 有个回答是说降低langchain的版本到0.0.174

你尝试之后，解决这个问题了吗？我己经降到0.0.174了，但出现了新的bug，关于langchain.shema.document的

**Comment by LMC117** [comment]
也可以不降低版本，debug看一下函数栈，给报错的函数加一个filter=None的参数就行。

**Comment by cuigang** [comment]
函数栈最后提示：

```
File "/Users/xxx/miniconda/envs/chatglm2/lib/python3.9/site-packages/langchain/vectorstores/faiss.py", line 263, in similarity_search_with_score
    docs = self.similarity_search_with_score_by_vector(
TypeError: similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'
```

在提示行附近，把filter参数那一行注释掉：

```
docs = self.similarity_search_with_score_by_vector(
            embedding,
            k,
            #filter=filter,
            fetch_k=fetch_k,
            **kwargs,
        )
```

问题解决，可以正常出结果了
