### ISSUE TITLE
[BUG] 请问api.py生产的接口调用中，knowledge_base_id 应该如何填写

### ISSUE THREAD

**Issue by tomFoxxxx** [imClumsyPanda/langchain-ChatGLM#875]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/49095654/7b771866-e54c-461c-935b-f450076f0eeb)
不知道这个参数应该如何设置才能和本地知识库对应上
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/49095654/79f3f401-3ec5-430e-8f46-0d063cf45a63)
这个是我的本地知识库，通过cli_demo.py生成的

**Comment by mario2rio** [comment]
knowledge_base下的每个目录名称

**Comment by tomFoxxxx** [comment]
> knowledge_base下的每个目录名称

谢谢 我通过调用下面的方法获取到了
`curl -X GET "http://127.0.0.1:7861/local_doc_qa/list_knowledge_base" \
  -H 'Accept: application/json'`

**Comment by tomFoxxxx** [comment]
> @tomFoxxxx 你好，你能详细说一下吗》我的本地多个文件怎么curl写呢？

这个接口是查看服务器端的存量知识库的，如果你要批量上传文件，需要使用/local_doc_qa/upload_files（上传知识库多个文件），入参请参考https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/docs/API.md

**Comment by tomFoxxxx** [comment]
谢谢大家
