### ISSUE TITLE
使用glm2-6b模型加载报错

### ISSUE THREAD

**Issue by qutcat1997** [imClumsyPanda/langchain-ChatGLM#876]
Loaded the model in 6.68 seconds.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ E:\langchain-ChatGLM-master\api.py:466 in <module>                                               │
│                                                                                                  │
│   463 │   args = parser.parse_args()                                                             │
│   464 │   args_dict = vars(args)                                                                 │
│   465 │   shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                                  │
│ ❱ 466 │   api_start(args.host, args.port)                                                        │
│   467                                                                                            │
│                                                                                                  │
│ E:\langchain-ChatGLM-master\api.py:449 in api_start                                              │
│                                                                                                  │
│   446 │   app.post("/local_doc_qa/update_file", response_model=BaseResponse)(update_doc)         │
│   447 │                                                                                          │
│   448 │   local_doc_qa = LocalDocQA()                                                            │
│ ❱ 449 │   local_doc_qa.init_cfg(                                                                 │
│   450 │   │   llm_model=llm_model_ins,                                                           │
│   451 │   │   embedding_model=EMBEDDING_MODEL,                                                   │
│   452 │   │   embedding_device=EMBEDDING_DEVICE,                                                 │
│                                                                                                  │
│ E:\langchain-ChatGLM-master\chains\local_doc_qa.py:136 in init_cfg                               │
│                                                                                                  │
│   133 │   │   │   │    top_k=VECTOR_SEARCH_TOP_K,                                                │
│   134 │   │   │   │    ):                                                                        │
│   135 │   │   self.llm = llm_model                                                               │
│ ❱ 136 │   │   self.embeddings = HuggingFaceEmbeddings(model_name=embedding_model_dict[embeddin   │
│   137 │   │   │   │   │   │   │   │   │   │   │   │   model_kwargs={'device': embedding_device   │
│   138 │   │   self.top_k = top_k                                                                 │
│   139                                                                                            │
│                                                                                                  │
│ C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\langchain\embed │
│ dings\huggingface.py:35 in __init__                                                              │
│                                                                                                  │
│    32 │                                                                                          │
│    33 │   def __init__(self, **kwargs: Any):                                                     │
│    34 │   │   """Initialize the sentence_transformer."""                                         │
│ ❱  35 │   │   super().__init__(**kwargs)                                                         │
│    36 │   │   try:                                                                               │
│    37 │   │   │   import sentence_transformers                                                   │
│    38                                                                                            │
│                                                                                                  │
│ E:\langchain-ChatGLM-master\pydantic\main.py:341 in pydantic.main.BaseModel.__init__             │
│                                                                                                  │
│ [Errno 2] No such file or directory: 'E:\\langchain-ChatGLM-master\\pydantic\\main.py'           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValidationError: 1 validation error for HuggingFaceEmbeddings
model_kwargs
  extra fields not permitted (type=value_error.extra)

**Comment by qutcat1997** [comment]
Loaded the model in 6.75 seconds.
ERROR 2023-07-18 14:35:14,056-1d: 1 validation error for HuggingFaceEmbeddings
model_kwargs
  extra fields not permitted (type=value_error.extra)

**Comment by qutcat1997** [comment]
解决了，原因是langchain版本的问题，我降了一个版本

**Comment by syn13355061266** [comment]
这个项目怎么接入glm2啊 已经可以接入了吗
