### ISSUE TITLE
求教如何查看日志

### ISSUE THREAD

**Issue by ye7love7** [imClumsyPanda/langchain-ChatGLM#877]
INFO  2023-07-18 09:05:35,372-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: /home/tskj/langchain-ChatGLM-0.1.16
flagging username: 161a7759ace54214b4223051ca525744
如何查看当前username的log，感谢！

**Comment by Gy1900** [comment]
老哥找到方法了吗

**Comment by ye7love7** [comment]
还没有，打算改一下代码，把日志直接保存成文件。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月19日(周三) 下午2:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] 求教如何查看日志 (Issue #877)




 
老哥找到方法了吗

**Comment by hzg0601** [comment]
本项目未设置日志
