### ISSUE TITLE
@czq001 @jszhangyili 按照报错信息 执行pip install sentence-transformers

### ISSUE THREAD

**Issue by jszhangyili** [imClumsyPanda/langchain-ChatGLM#885]
@czq001 @jszhangyili 按照报错信息 执行pip install sentence-transformers

_Originally posted by @imClumsyPanda in https://github.com/imClumsyPanda/langchain-ChatGLM/issues/400#issuecomment-1641418919_
            没用，执行了也都是安装成功的，但是还是无法import。python版本3.10

**Comment by imClumsyPanda** [comment]
本地项目路径下或是环境变量里有同名文件夹吗

jszhangyili ***@***.***>于2023年7月19日 周三13:27写道：

**Comment by hzg0601** [comment]
请考虑安装环境与执行代码的环境是否一致
