### ISSUE TITLE
[BUG] webui.py init_model() 初始化问题

### ISSUE THREAD

**Issue by blackxer** [imClumsyPanda/langchain-ChatGLM#889]
初始化时没有设置 LLM_HISTORY_LEN 历史变量。

第108 行代码 ：
llm_model_ins = shared.loaderLLM()
 后面是否应该加上：
llm_model_ins.history_len = LLM_HISTORY_LEN
初始化历史对话轮数

**Comment by liunux4odoo** [comment]
该问题已在[dev分支 a6f42e7](https://github.com/imClumsyPanda/langchain-chatGLM/commit/a6f42e7c8e60ee3dcf725d2995ad2a47bf26a8c3)修复。
