### ISSUE TITLE
怎么做账户管理，知识库隔离

### ISSUE THREAD

**Issue by guiniao** [imClumsyPanda/langchain-ChatGLM#892]
目前部署的，根据ip+端口不需要用户名和密码，如果想实现多租户用账号密码登陆，且不同的用户只能看到自己的知识库，请问有什么快速的实现方法吗，感谢

**Comment by MostGangsta** [comment]
提供个想法 修改knowledge_base下faiss文件夹目录结构生成规则，每个用户唯一标识或者token啥的对应一个，加载faiss时指定文件夹

**Comment by guiniao** [comment]
大佬，具体咋实现，knowledge_base，这个生成的代码在哪里



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] 怎么做账户管理，知识库隔离 (Issue #892)




 
提供个想法 修改knowledge_base下faiss文件夹目录结构生成规则，每个用户唯一标识或者token啥的对应一个，加载faiss时指定文件夹

**Comment by RudRho** [comment]
> 提供个想法 修改knowledge_base下faiss文件夹目录结构生成规则，每个用户唯一标识或者token啥的对应一个，加载faiss时指定文件夹

如果可以，请提交一个PR

**Comment by hzg0601** [comment]
本项目目前没有支持该功能的计划，如果有能力欢迎提交PR
