### ISSUE TITLE
使用glm2-6b时报错，想问一下需要怎么修改啊

### ISSUE THREAD

**Issue by syn13355061266** [imClumsyPanda/langchain-ChatGLM#899]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:12<00:00,  1.82s/it]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/zyk/syn/langchain-ChatGLM-master/webui.py:322 in <module>                                  │
│                                                                                                  │
│   319 """                                                                                        │
│   320                                                                                            │
│   321 # 初始化消息                                                                               │
│ ❱ 322 model_status = init_model()                                                                │
│   323                                                                                            │
│   324 default_theme_args = dict(                                                                 │
│   325 │   font=["Source Sans Pro", 'ui-sans-serif', 'system-ui', 'sans-serif'],                  │
│                                                                                                  │
│ /home/zyk/syn/langchain-ChatGLM-master/webui.py:103 in init_model                                │
│                                                                                                  │
│   100 │                                                                                          │
│   101 │   args_dict = vars(args)                                                                 │
│   102 │   shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                                  │
│ ❱ 103 │   llm_model_ins = shared.loaderLLM()                                                     │
│   104 │   llm_model_ins.set_history_len(LLM_HISTORY_LEN)                                         │
│   105 │   try:                                                                                   │
│   106 │   │   local_doc_qa.init_cfg(llm_model=llm_model_ins)                                     │
│                                                                                                  │
│ /home/zyk/syn/langchain-ChatGLM-master/models/shared.py:40 in loaderLLM                          │
│                                                                                                  │
│   37 │   if 'FastChatOpenAILLM' in llm_model_info["provides"]:                                   │
│   38 │   │   loaderCheckPoint.unload_model()                                                     │
│   39 │   else:                                                                                   │
│ ❱ 40 │   │   loaderCheckPoint.reload_model()                                                     │
│   41 │                                                                                           │
│   42 │   provides_class = getattr(sys.modules['models'], llm_model_info['provides'])             │
│   43 │   modelInsLLM = provides_class(checkPoint=loaderCheckPoint)                               │
│                                                                                                  │
│ /home/zyk/syn/langchain-ChatGLM-master/models/loader/loader.py:419 in reload_model               │
│                                                                                                  │
│   416 │   │   │   except Exception as e:                                                         │
│   417 │   │   │   │   print("加载PrefixEncoder config.json失败")                                 │
│   418 │   │                                                                                      │
│ ❱ 419 │   │   self.model, self.tokenizer = self._load_model(self.model_name)                     │
│   420 │   │                                                                                      │
│   421 │   │   if self.lora:                                                                      │
│   422 │   │   │   self._add_lora_to_model([self.lora])                                           │
│                                                                                                  │
│ /home/zyk/syn/langchain-ChatGLM-master/models/loader/loader.py:145 in _load_model                │
│                                                                                                  │
│   142 │   │   │   │   │   │   else:                                                              │
│   143 │   │   │   │   │   │   │   self.device_map = self.chatglm_auto_configure_device_map(num   │
│   144 │   │   │   │   │                                                                          │
│ ❱ 145 │   │   │   │   │   model = dispatch_model(model, device_map=self.device_map)              │
│   146 │   │   │   else:                                                                          │
│   147 │   │   │   │   model = (                                                                  │
│   148 │   │   │   │   │   LoaderClass.from_pretrained(                                           │
│                                                                                                  │
│ /home/zyk/.conda/envs/syn6/lib/python3.10/site-packages/accelerate/big_modeling.py:330 in        │
│ dispatch_model                                                                                   │
│                                                                                                  │
│   327 │   if not is_torch_version(">=", "1.9.0"):                                                │
│   328 │   │   raise NotImplementedError("Model dispatching requires torch >= 1.9.0")             │
│   329 │   # Error early if the device map is incomplete.                                         │
│ ❱ 330 │   check_device_map(model, device_map)                                                    │
│   331 │                                                                                          │
│   332 │   if main_device is None:                                                                │
│   333 │   │   if set(device_map.values()) == {"cpu"} or set(device_map.values()) == {"cpu", "d   │
│                                                                                                  │
│ /home/zyk/.conda/envs/syn6/lib/python3.10/site-packages/accelerate/utils/modeling.py:902 in      │
│ check_device_map                                                                                 │
│                                                                                                  │
│    899 │   │   │   ]                                                                             │
│    900 │   if len(all_model_tensors) > 0:                                                        │
│    901 │   │   non_covered_params = ", ".join(all_model_tensors)                                 │
│ ❱  902 │   │   raise ValueError(                                                                 │
│    903 │   │   │   f"The device_map provided does not give any device for the following paramet  │
│    904 │   │   )                                                                                 │
│    905                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: The device_map provided does not give any device for the following parameters: transformer.embedding.word_embeddings.weight, transformer.rotary_pos_emb.inv_freq, 
transformer.encoder.layers.0.input_layernorm.weight, transformer.encoder.layers.0.self_attention.query_key_value.weight, transformer.encoder.layers.0.self_attention.query_key_value.bias, 
transformer.encoder.layers.0.self_attention.dense.weight, transformer.encoder.layers.0.post_attention_layernorm.weight, transformer.encoder.layers.0.mlp.dense_h_to_4h.weight, 
transformer.encoder.layers.0.mlp.dense_4h_to_h.weight, transformer.encoder.layers.1.input_layernorm.weight, transformer.encoder.layers.1.self_attention.query_key_value.weight, 
transformer.encoder.layers.1.self_attention.query_key_value.bias, transformer.encoder.layers.1.self_attention.dense.weight, transformer.encoder.layers.1.post_attention_layernorm.weight, 
transformer.encoder.layers.1.mlp.dense_h_to_4h.weight, transformer.encoder.layers.1.mlp.dense_4h_to_h.weight, transformer.encoder.layers.2.input_layernorm.weight, 
transformer.encoder.layers.2.self_attention.query_key_value.weight, ............

**Comment by hzg0601** [comment]
拉最新的dev分支代码

**Comment by sujinzihan** [comment]
在 loader.py文件中增加
        # Load the model in simple 16-bit mode by default
        # 如果加载没问题，但在推理时报错RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`
        # 那还是因为显存不够，此时只能考虑--load-in-8bit,或者配置默认模型为`chatglm-6b-int8`
        if "chatglm2" in self.model_name.lower():
            self.device_map = None
加在上面这段注释下面
