### ISSUE TITLE
关于VECTOR_SEARCH_SCORE_THRESHOLD 参数的BUG！

### ISSUE THREAD

**Issue by cristianohello** [imClumsyPanda/langchain-ChatGLM#903]
实践中发现，VECTOR_SEARCH_SCORE_THRESHOLD 越低召回的越少？

# 知识检索内容相关度 Score, 数值范围约为0-1100，如果为0，则不生效，经测试设置为小于500时，匹配结果更精准
#VECTOR_SEARCH_SCORE_THRESHOLD = 10
VECTOR_SEARCH_SCORE_THRESHOLD = 10

**Comment by Vincent-ch99** [comment]
#896 看这里我的回复

**Comment by hzg0601** [comment]
已有答案，关闭此issue
