### ISSUE TITLE
cli_demo.py执行后，会输出无关的信息！如何改源码去掉。

### ISSUE THREAD

**Issue by cristianohello** [imClumsyPanda/langchain-ChatGLM#908]
我想把：
__call:已知信息：。。。。。。。无关这些信息去掉。

我问你好，输出_call等无关信息，在哪去掉这些信息，我只需要：
问题是：你好
你好！有什么我可以帮助你的吗？

Input your question 请输入问题：你好
__call:已知信息：
意大利裁判达尼埃莱·奥萨托当选最佳裁判。 2022年卡塔尔世界杯决赛，于2022年12月18日在卢赛尔体育场举行，以决出2022年卡塔尔世界杯冠军归属，对阵双方为阿根廷与法国。 最终阿根廷队以7:5(点球大战4:2)击败卫冕冠军法国队，时隔36年再次捧起大力神杯。 你好。卡塔尔世界杯冠军是谁？ 阿根廷。

根据上述已知信息，简洁和专业的来回答用户的问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题” 或 “没有提供足够的相关信息”，不允许在答案中添加编造成分，答案请使用中文。 问题是：你好
你好！有什么我可以帮助你的吗？

出处 [1] test100.txt：

意大利裁判达尼埃莱·奥萨托当选最佳裁判。 2022年卡塔尔世界杯决赛，于2022年12月18日在卢赛尔体育场举行，以决出2022年卡塔尔世界杯冠军归属，对阵双方为阿根廷与法国。 最终阿根廷队以7:5(点球大战4:2)击败卫冕冠军法国队，时隔36年再次捧起大力神杯。 你好。

**Comment by hzg0601** [comment]
cli_demo默认为知识问答设计，如不需要知识问答，可以选择api.py,webui.py
