### ISSUE TITLE
[BUG]在web界面点击重新加载模型会报错

### ISSUE THREAD

**Issue by znzjugod** [imClumsyPanda/langchain-ChatGLM#910]
**问题描述 / Problem Description**
在web界面点击重新加载模型会报错。报错信息如下：
ERROR 2023-07-22 18:07:09,843-1d: 'THUDM/chatglm-6b'
ERROR 2023-07-22 18:07:16,619-1d: 'THUDM/chatglm-6b'
ERROR 2023-07-22 18:07:23,947-1d: 'THUDM/chatglm-6b'

**复现问题的步骤 / Steps to Reproduce**
在web界面点击重新加载模型

**预期的结果 / Expected Result**
成功重新加载

**实际结果 / Actual Result**
重新加载失败 

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：master最新代码
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：text2vec-large-chinese 
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: python 3.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
如果是加载本地模型，启动时加上参数`--no-remote-model`，或者把配置文件里对应llm模型的pretrained_name设置成和name一样试试？

**Comment by znzjugod** [comment]
> 如果是加载本地模型，启动时加上参数`--no-remote-model`，或者把配置文件里对应llm模型的pretrained_name设置成和name一样试试？

thanks
