### ISSUE TITLE
[BUG] pip install -r requirements.txt的时候，安装pymupdf一直报错

### ISSUE THREAD

**Issue by c4fun** [imClumsyPanda/langchain-ChatGLM#918]
**问题描述 / Problem Description**
pip install -r requirements.txt的时候，安装pymupdf一直报错. 

**复现问题的步骤 / Steps to Reproduce**
**方法一**
1. 创建一个新的conda环境，其执行器为python 3.10。并使用`conda activate 环境名`来切换环境
2. 转到当前项目主文件夹，执行`pip install -r requirements.txt`
3. 问题出现：`ERROR: Could not build wheels for pymupdf, which is required to install pyproject.toml-based projects`

**方法二：预装pymupdf**
1. 创建一个新的conda环境，其执行器为python 3.10。并使用`conda activate 环境名`来切换环境
2. `pip install pymupdf`，没有问题。
3. 在requirements.txt中删掉mymupdf这一行。
4. 转到当前项目主文件夹，执行`pip install -r requirements.txt`
5. 问题出现：`ERROR: Could not build wheels for pymupdf, which is required to install pyproject.toml-based projects`

**预期的结果 / Expected Result**
应当能够安装成功，这样可以进行下一步

**实际结果 / Actual Result**
1. 在pymupdf这一步，有点卡住的情况
2. 安装失败，提示`ERROR: Could not build wheels for pymupdf, which is required to install pyproject.toml-based projects`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.1.16
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：N/A。未到这一步。
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：N/A。未到这一步。
- 操作系统及版本 / Operating system and version: macos Ventura 13.4。M1 PRO
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
```
      mkdir -p build/release/ ; xcrun cc -Wl,-dead_strip -Wl,-s -o build/release/muraster build/release/source/tools/muraster.o build/release/libmupdf.a build/release/libmupdf-third.a build/release/libmupdf-pkcs7.a build/release/libmupdf-threads.a  -lm           -lpthread -lstdc++   -L/opt/homebrew/Cellar/openssl@3/3.1.1_1/lib -lcrypto
      ld: warning: option -s is obsolete and being ignored
      build/release:
      total 161304
      drwxr-xr-x   3 macuser  staff        96 Jul 24 10:19 generated
      -rw-r--r--   1 macuser  staff     17200 Jul 24 10:22 libmupdf-pkcs7.a
      -rw-r--r--   1 macuser  staff  12913480 Jul 24 10:22 libmupdf-third.a
      -rw-r--r--   1 macuser  staff      2080 Jul 24 10:22 libmupdf-threads.a
      -rw-r--r--   1 macuser  staff  48714864 Jul 24 10:19 libmupdf.a
      -rwxr-xr-x   1 macuser  staff   9039461 Jul 24 10:22 muraster
      -rwxr-xr-x   1 macuser  staff  11888515 Jul 24 10:22 mutool
      drwxr-xr-x  11 macuser  staff       352 Jul 24 10:22 source
      drwxr-xr-x  14 macuser  staff       448 Jul 24 10:22 thirdparty
      PyMuPDF/setup.py: Finished building mupdf.
      PyMuPDF/setup.py: sys.platform='darwin'
      PyMuPDF/setup.py: library_dirs=['mupdf-1.20.3-source/build/release', 'mupdf-1.20.3-source/build/release']
      PyMuPDF/setup.py: libraries=['mupdf', 'mupdf-third']
      PyMuPDF/setup.py: include_dirs=['mupdf-1.20.3-source/include', 'mupdf-1.20.3-source/include/mupdf', 'mupdf-1.20.3-source/thirdparty/freetype/include']
      PyMuPDF/setup.py: extra_link_args=[]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'fitz._fitz' extension
      swigging fitz/fitz.i to fitz/fitz_wrap.c
      swig -python -o fitz/fitz_wrap.c fitz/fitz.i
      error: command 'swig' failed: No such file or directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymupdf
  Running setup.py clean for pymupdf
Failed to build pymupdf
ERROR: Could not build wheels for pymupdf, which is required to install pyproject.toml-based projects
```

**Comment by c4fun** [comment]
# 解决方法：安装swig即可
从第一次报错消息中：
```
error: command 'swig' failed: No such file or directory
```
可以看到是swig的问题。

## 解决方法
所以，直接使用自己习惯的安装器安装swig即可，例如使用brew：
`brew install swig`

**Comment by 903496130** [comment]
@c4fun c4fun 我的超人！
