### ISSUE TITLE
[BUG] 调用chatgpt API出现Failed to establish a new connection问题，按照注释处理无效

### ISSUE THREAD

**Issue by tanglu86** [imClumsyPanda/langchain-ChatGLM#922]
1、服务器是日本的，直接使用curl调用openai API是可以的，节点没有被墙

2、已经将Embedding模型下载到了本地，然后pip3 install urllib3==1.25.11，将https改为http，configs/model_config.py相关配置如下：
![2](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38269740/04560077-050a-4c93-a374-1eee7e4adcde)

3、python3 webui.py的时候依然出现了Failed to establish a new connection的问题
![1](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38269740/3dae45c4-4752-450c-8cd3-4a7a4d87ffb2)

4、DNS也是正常的，但是为什么出现了 Name or service not known的错呢

![3](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38269740/fa932159-aef3-4799-97bb-b2f40692fad1)

**Comment by hzg0601** [comment]
依次试试这两个吧
![6aad2c0ce4b09a49599126c0a43ec53](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/22924096/b1fd6497-a3ee-4b1d-a5dd-8a6e1c4115e6)

![b762da4c352e72d1480379c1544a9bd](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/22924096/ff922389-4a44-4066-9a15-eeb290ab7069)
