### ISSUE TITLE
new feature: 添加对P-tunningv2微调后的模型支持

### ISSUE THREAD

**Issue by thaumstrial** [imClumsyPanda/langchain-ChatGLM#99]
能否添加新的功能，对使用[P-tunningv2](https://github.com/THUDM/ChatGLM-6B/tree/main/ptuning)微调chatglm后的模型提供加载支持

**Comment by thaumstrial** [comment]
我本地写好了，用得上这个功能吗

**Comment by imClumsyPanda** [comment]
可以有！厉害了，请问测试了效果吗

Thaumstrial ***@***.***>于2023年4月15日 周六03:05写道：

**Comment by imClumsyPanda** [comment]
您可以提PR到dev branch感谢🙏

**Comment by imClumsyPanda** [comment]
已完成 merge 感谢贡献🙏
